### ISSUE TITLE
Title Tag is Getting Double-Encoded When Ampersand Exists

### ISSUE THREAD

**Issue by shefik** [zikula/core#3594] opened 2017-05-29 10:11 UTC
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.6
| PHP Version       | 5.6

### Expected behavior

The `<title>` tag should not be double-encoded, when an ampersand exists in the title

### Actual behavior

The `<title>` tag is displaying with double encoding for ampersands.

### Steps to reproduce

Set a title as example `Now & Then`. The output in the `<title>` tag is currently `Now &amp;amp Then`.

**Comment by shefik** [comment] 2017-05-29 10:29
What appears to fix the issue in the template is applying the `safeHtml` filter:

```<title>{{ pagevars.title|safeHtml }}</title>```

However, that doesn't fix the problem to begin with, where the double-encoding occurs somewhere beforehand.

**Comment by Portugao** [comment] 2017-05-29 11:39
I can reproduce.

**Comment by craigh** [comment] 2017-06-02 21:13
> Steps to reproduce
> Set a title...

can you be more specific how you did that?

**Comment by shefik** [comment] 2017-06-02 21:20
@craigh Just set a page var for the title (as you would do normally to set a title var). Make sure that it has an ampersand in the title.

**Comment by craigh** [comment] 2017-06-02 21:43
I'm sorry to seem so dumb.... Do you mean in the General Settings for Site name?
![screen shot 2017-06-02 at 5 42 38 pm](https://cloud.githubusercontent.com/assets/350048/26745911/e501961a-47ba-11e7-8059-3ce5c38608c4.png)

Or are you using a module? I guess I never do this, so I am lost.

**Comment by shefik** [comment] 2017-06-02 22:07
I am resetting the title var via a module. Although I do initially have a title set in the Settigs module. The subsequent call to set the title overrides the settings module as expected. Either way, using an ampersand in the title is an issue with double-encoding.

**Comment by craigh** [comment] 2017-06-02 22:43
![screen shot 2017-06-02 at 6 42 43 pm](https://cloud.githubusercontent.com/assets/350048/26747373/520662a6-47c3-11e7-9245-c80b95b94bc2.png)

This appears to be working as expected. what am I not understanding?

**Comment by shefik** [comment] 2017-06-02 23:06
Try this to code to reproduce the error. Insert this code in a Twig template:

```{{ pageSetVar('title', __('This & That')) }}```

**Comment by craigh** [comment] 2017-06-02 23:51
ok - I think I understand now, but I still don't think I am getting the error?

![screen shot 2017-06-02 at 7 50 16 pm](https://cloud.githubusercontent.com/assets/350048/26748569/d6f6b714-47cc-11e7-89b5-b34e3dedb0ca.png)

**Comment by shefik** [comment] 2017-06-03 00:10
I'm not sure why you are not able to replicate the error. However, as I mentioned earlier, I discovered a way to fix via the template. I changed the code to this, to apply the `safeHtml` filter:

```<title>{{ pagevars.title|safeHtml }}</title>```

I don't have the issue anymore. But, that doesn't fix the problem to begin with, where the double-encoding occurs somewhere beforehand. Not sure exactly where though, and I looked through the code.

**Comment by craigh** [comment] 2017-06-03 02:15
I'm wondering if your data is encoded.

**Comment by craigh** [comment] 2017-06-03 13:43
I tried it with Pages and it also works with persisted data as expected. My guess is that your data is encoded in the DB and so it gets encoded again when displayed. This would be a mistake of the module persisting the data in the first place (into the DB) because Doctrine doesn't encode data when persisting, so the responsible module must be doing more work than required. 

![screen shot 2017-06-03 at 9 39 31 am](https://cloud.githubusercontent.com/assets/350048/26754019/b63d3362-4840-11e7-89ba-f02d477ba6ca.png)

**Comment by craigh** [comment] 2017-06-08 22:52
ping @shefik did you give this up? should I close it?

**Comment by Portugao** [comment] 2017-06-10 20:31
For me it's not clear if it is a core issue or not; maybe we can hear @Guite when he is back from holidays.

**Comment by craigh** [comment] 2017-06-10 21:23
The question isn't for @Guite , the question is for @shefik . Is the data encoded or isn't it? If so, how did it get encoded? 

@Portugao wrote:
> I can reproduce.

Where? how? Please - I would like to confirm the problem. Do you know if _your're_ data is encoded?

**Comment by Portugao** [comment] 2017-06-11 19:29
No, I do not know. My module is a MOST module and that's the reason, for that I suggesting to wait for @Guite .

**Comment by Guite** [comment] 2017-06-16 09:29
MOST modules do not encode their data programmatically (anymore). Instead they rely on Twig (and Twig filters like `safeHtml`) for output sanitizing.

**Comment by Portugao** [comment] 2017-06-16 10:09
Hi Axel, very strange because I have the same issue.
The title of an entity in the page is correctly shown and the title in the browser has this issue.

**Comment by craigh** [comment] 2017-06-16 12:16
please show (like I have above) what the data looks like in your DB. then the mystery will be over.

![b63d3362-4840-11e7-89ba-f02d477ba6ca](https://user-images.githubusercontent.com/350048/27226247-0b8165ac-526c-11e7-8830-eb396dcd7344.png)

**Comment by craigh** [comment] 2017-06-19 11:17
Feedback required. @Portugao @shefik

**Comment by craigh** [comment] 2017-07-08 11:03
closing for lack of response

**Closed by craigh** 2017-07-08 11:03 UTC
Labels: Feedback required
