### ISSUE TITLE
Zikula\RoutesModule\Controller\RedirectingcontrollerController class was not found

### ISSUE THREAD

**Issue by rallek** [zikula/core#2552] opened 2015-08-02 12:32 UTC
I installed Zikula 1.4.0 together with News-master, Content-master, EZComments-master and Akismet-master. Direct after installation I went to the admin area of news and want to see the preview of the News introduction article. There I got the following error:
````
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

The _controller value "ZikulaRoutesModule:Redirectingcontroller:Removetrailingslash" maps to a "Zikula\RoutesModule\Controller\RedirectingcontrollerController" class, but this class was not found. Create this class or check the spelling of the class and its namespace.
````
Short URL on and off makes no difference. 
@espaan  @cmfcmf  Known issue?

There is no hint of a news error so I placed it at the core.

**Comment by rallek** [comment] 2015-08-02 12:49
after creating a new news it seems to work. It is an initialisation error I think.

**Comment by cmfcmf** [comment] 2015-08-09 14:11
This is caused by my Speed Improvements PR :-( Will need to look into it.

**Comment by rallek** [comment] 2015-08-10 17:50
this is potentially also the bug why news is not working in short URL mode I guess.

**Comment by cmfcmf** [comment] 2015-08-25 12:11
Fixed by #2568.

**Closed by cmfcmf** 2015-08-25 12:11 UTC
Labels: Bug

**Comment by craigh** [comment] 2015-08-25 14:32
@cmfcmf does this issue make 1.4.0 non-functional? Should we release 1.4.1 hotfix with this commit (at least)?

**Comment by cmfcmf** [comment] 2015-08-28 08:52
I wouldn't say "non-functional". I am not sure whether I want to go through the release process again right now.
