### ISSUE TITLE
Pageaddvars uses wrong path if Zikula installed in subdirectory

### ISSUE THREAD

**Issue by ccandreva** [zikula/core#2892] opened 2016-06-01 17:19 UTC
| Q | A |
| --- | --- |
| Zikula Version | 1.4.2 |
| PHP Version | 5.6.21 |

If Zikula is installed in a subdirectory (http://www.site.com/ZIkula/) , it appears that the pageaddvars function isn't prepending the subdirectory to the javascript path. This can be seen on a fresh install to a subdirectory by attempting to add a menu item to the default Main Menu extblock and viewing source or console in Firebug
### Expected behavior

Javescript loaded from /Zikula/javascript/... , 
Clicking "Create New Menu Item" works
### Actual behavior

Javascript files are loaded  from "/javascript/..." which does not exist.
Clicking "Create New Menu Item" brings you to the top of the page.
### Steps to reproduce

Install ZIkula 1.4.2 in a subdirectory of a web site
Open firebug, bring up console.
Go to Admin -> Blocks , edit the Main Menu Ext block
Notice errors in console window.
view source, look for javascript lines in header.
Click "Create New Menu Item"

**Comment by craigh** [comment] 2016-06-01 19:14
please take a look elsewhere in core modules to see how it works. I'm not certain, and don't have the time to look, but I'm quite sure you are responsible to provide the proper path using either `asset` or `zasset` functions.

**Comment by craigh** [comment] 2016-06-01 21:20
sorry - I mis-read the initial ticket. previous comment deleted.

**Comment by craigh** [comment] 2016-06-01 21:21
> Notice errors in console window.

please post the errors in the ticket here.

**Comment by ccandreva** [comment] 2016-06-02 12:46
Zikula is running on localhost on my Fedora desktop in /var/www/html/Zikula
Screenshot of Firebug errors:
![screenshot from 2016-06-02 08-40-49](https://cloud.githubusercontent.com/assets/511819/15745053/d1a4eb0e-289d-11e6-9166-805b7aeda9d1.png)

Cut and paste of lines from show source. Note the three "/javascipt/helpers/" lines in the middle not prefixed with "/Zikula/" 
```
<script type="text/javascript" src="/Zikula/javascript/ajax/proto_scriptaculous.combined.min.js"></script>
<script type="text/javascript" src="/Zikula/web/jquery/jquery.min.js"></script>
<script type="text/javascript" src="/Zikula/web/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/Zikula/javascript/helpers/bootstrap-zikula.js"></script>
<script type="text/javascript" src="/Zikula/web/html5shiv/dist/html5shiv.js"></script>
<script type="text/javascript" src="/Zikula/web/bundles/fosjsrouting/js/router.js"></script>
<script type="text/javascript" src="/Zikula/js/routing?callback=fos.Router.setData"></script>
<script type="text/javascript" src="/Zikula/javascript/jquery_config.js"></script>
<script type="text/javascript" src="/Zikula/web/jquery/jquery-migrate.min.js"></script>
<script type="text/javascript" src="/Zikula/javascript/livepipe/livepipe.combined.min.js"></script>
<script type="text/javascript" src="/javascript/helpers/Zikula.js"></script>
<script type="text/javascript" src="/javascript/helpers/Zikula.UI.js"></script>
<script type="text/javascript" src="/javascript/helpers/Zikula.itemlist.js"></script>
<script type="text/javascript" src="/Zikula/system/AdminModule/Resources/public/js/admin_admin_systemnotices.js"></script>
<script type="text/javascript" src="/Zikula/system/AdminModule/Resources/public/js/jQuery.mmenu-5.5.1/dist/core/js/jquery.mmenu.min.all.js"></script>
<script type="text/javascript" src="/Zikula/system/AdminModule/Resources/public/js/admin_admin_admintabs.js"></script>
<script type="text/javascript" src="/Zikula/system/BlocksModule/Resources/public/js/Zikula.Blocks.Admin.Edit.js"></script>
<script type="text/javascript" src="/Zikula/web/bootstrap-jqueryui/bootstrap-jqueryui.min.js"></script>
```

**Comment by Guite** [comment] 2016-07-15 13:47
Can't reproduce this one:

```
<script type="text/javascript" src="/src/javascript/jquery_config.js"></script>
<script type="text/javascript" src="/src/web/jquery/jquery-migrate.min.js"></script>
<script type="text/javascript" src="/src/javascript/livepipe/livepipe.combined.min.js"></script>
<script type="text/javascript" src="/src/javascript/helpers/Zikula.js"></script>
<script type="text/javascript" src="/src/javascript/helpers/Zikula.UI.js"></script>
<script type="text/javascript" src="/src/javascript/helpers/Zikula.itemlist.js"></script>
```

The `/src` prefix is prepended to all scripts.

**Comment by Guite** [comment] 2016-07-15 13:48
@ccandreva could you please retest using 1.4.3-git (the `1.4` branch)?

**Comment by Guite** [comment] 2016-07-26 20:24
ping @ccandreva

**Comment by Guite** [comment] 2016-08-14 08:21
Closing. @ccandreva reopen if you still experience this issue using 1.4.3.

**Comment by ccandreva** [comment] 2017-01-23 14:21
Sorry for dropping out, I've re-confirmed this again in 1.4.5 , using the bootstrap theme. Exact same behavior as above.

**Comment by craigh** [comment] 2017-01-24 10:12
@ccandreva there must be something different about your set up because my local install is ALWAYS in a subdirectory and I do not get these errors - nor did @Guite . So we would need your help in discerning the difference.

**Comment by craigh** [comment] 2017-01-24 10:15
> Go to Admin -> Blocks , edit the Main Menu Ext block

btw - this doesn't exist in 1.4.5

**Comment by craigh** [comment] 2017-01-24 22:28
unable to reproduce:
![screen shot 2017-01-24 at 5 27 54 pm](https://cloud.githubusercontent.com/assets/350048/22269687/7fb1eb68-e25a-11e6-864a-10d1b3f7e5a5.png)

**Comment by ccandreva** [comment] 2017-01-25 13:29
OK, this happened on my upgraded site. I will try a clean install, hopefully at lunch.

**Comment by craigh** [comment] 2017-01-26 00:56
how did you do the upgrade? http? cli?

**Comment by ccandreva** [comment] 2017-01-26 13:26
http .

Didn't get a chance to do the fresh install yesterday.

**Comment by craigh** [comment] 2017-01-29 23:17
status?

**Comment by ccandreva** [comment] 2017-01-31 17:51
OK, I've confirmed this in a fresh installed of Zikula 1.4.5 . I reproduced by trying to add an ExtMenu block. The new Firefox debugger doesn't show the paths in the window so a screenshot is basicly useless, but Zikula.js, Zikula.UI.js, and Zikula.itemlist.js all try to load from /javascript/... instead of from /Zikula/javascript/...

**Comment by craigh** [comment] 2017-01-31 21:48
@ccandreva I guess I will need your assistance in tracking this further. the place you want to look in the code is [here](https://github.com/zikula/core/blob/7f218fba57e38b38df3486673b4cf0ce3c48e6ed/src/system/ThemeModule/Engine/Engine.php#L399-L400).

first - what is your value for `compat_layer` in `custom_parameters.yml`?

If you can enable a breakpoint in there and determine what values are present when trying to load those scripts, that would be helpful.

**Comment by craigh** [comment] 2017-01-31 22:14
please also report the value of `router.request_context.base_url` in your `custom_parameters.yml` file.

**Comment by craigh** [comment] 2017-01-31 22:18
my guess is the the `$baseUri` [here](https://github.com/zikula/core/blob/7f218fba57e38b38df3486673b4cf0ce3c48e6ed/src/system/ThemeModule/Engine/Engine.php#L393-L393) is somehow empty and causing these problems. The trouble is this value is pulled by symfony, so figuring our why it is getting a wrong value could be difficult.

**Comment by craigh** [comment] 2017-02-01 01:32
also what OS/webserver are you running?

**Comment by ccandreva** [comment] 2017-02-01 14:08
compat_layer: true
router.request_context.base_url: /Zikula

This test is on Fedora 25, Apache 2.4.25, php 7.0.15  . Also seen on RHEL 7, httpd 2.4.18, php 5.5.21

I used an error_log after Engine.php:393 to dump $baseUri, it is '/Zikula'

**Comment by craigh** [comment] 2017-02-01 14:16
> I used an error_log after Engine.php:393 to dump $baseUri, it is '/Zikula'

I'm guessing it is not _always_ `/Zikula` - please check instance where `false !== strpos($javascript, 'Zikula.')`

**Comment by ccandreva** [comment] 2017-02-01 14:29
I think you just hit the nail on the head - the three files that are not having the path prepended all start with Zikula, and my baseUri is Zikula. Most likely the problem is line 399:
`$javascript = (!empty($baseUri) && (false === strpos($javascript, $baseUri))) ? "$baseUri/$javascript" : "$javascript";`

Any time the javascript file name happens to contain the baseUri, that strpos won't return false, so the baseUri isn't prepended. It could probably be fixed as:
`strpos($javascript, $baseUri. '/')`

**Comment by craigh** [comment] 2017-02-01 14:30
AH!

good catch. I'll look into it more carefully tonight. thanks!

**Comment by ccandreva** [comment] 2017-02-01 14:36
More specificly, if the baseUri has to start with a '/' then this will only hit when the baseUri is the prefix of the file name. Either way adding the trailing '/' makes the strpos more specific. If we are sure the baseUri should never end with a '/' then the blind "add a /" method works, otherwise it may be necessary to check for it first.

**Comment by ccandreva** [comment] 2017-02-01 14:44
Also, the check should really be that the strpos doesn't return 0, since the baseURI could be a component of the path. For example I might have a Zikula install for developing a module installed in a subdir named after the module. Of course, this will then break if I call my baseUri /system/ for some reason.

In what instance would the baseUri already be applied at this point, making this check necessary ?

**Closed** 2017-02-01 20:33 UTC
Labels: Bug, Feedback required, unconfirmed
