### ISSUE TITLE
CLI router error

### ISSUE THREAD

**Issue by craigh** [zikula/core#2714] opened 2015-12-27 14:38 UTC
```
Craigs-MacBook-Air:src craig$ php app/console debug:router
                                                                                                                       
  [Symfony\Component\Config\Exception\FileLoaderLoadException]                                                         
  Warning: Class __PHP_Incomplete_Class has no unserializes in
@TwigBundle/Resources/config/routing/errors.xml (which is being imported from
"/Applications/MAMP/htdocs/core.git/src/app/config/routing_dev.yml").
Make sure the "TwigBundle" bundle is correctly registered and loaded in the application
kernel class. If the bundle is registered, make sure the bundle path
"@TwigBundle/Resources/config/routing/errors.xml" is not empty.                                 
                                                             
  [Symfony\Component\Debug\Exception\ContextErrorException]  
  Warning: Class __PHP_Incomplete_Class has no unserializer  
```

**Comment by craigh** [comment] 2016-01-07 10:50
This happens because something is not registered in the `dev` environment that is correctly loaded in the `prod` environment. If you do `php app/console debug:router -e=prod` then it works fine.

**Comment by cmfcmf** [comment] 2016-08-27 13:28
This should be fixed by https://github.com/zikula/core/pull/2969 and is a duplicate of https://github.com/zikula/core/issues/2883

**Closed by cmfcmf** 2016-08-27 13:28 UTC
Labels: Routing
