### ISSUE TITLE
news can not be used on zikula 1.5.0

### ISSUE THREAD

**Issue by rallek** [zikula/core#3694] opened 2017-07-24 17:29 UTC
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.5.0 ci build 231
| PHP Version       | 5.6

### Expected behavior
News is working as always

### Actual behavior
see https://github.com/zikula-modules/News/issues/159
Compatibility of old modules seems to be broken.

### Steps to reproduce
change the version of zikula inside news to something bigger than 1.5.0 and use News after an upgrade.

**Comment by Guite** [comment] 2017-07-24 17:31
The `sort_value` field was removed from `CategoryEntity`: https://github.com/zikula/core/pull/3494/files#diff-f1e2d9d43205b53a2554605229a5ab3cL71

It is still used as default value in several methods of `CategoryApi` though:

- getSubCategories
- getSubCategoriesByPath
- getSubCategoriesForCategory

@craigh

**Comment by Guite** [comment] 2017-07-25 11:51
@rallek please test the probable fix at https://github.com/zikula/core/pull/3700

**Comment by rallek** [comment] 2017-07-25 18:03
please reopen. Same problem with ci build 239!
````
Error in DBUtil::executeSQL: SELECT id AS "id",parent_id AS "parent_id",is_locked AS "is_locked",is_leaf AS "is_leaf",name AS "name",value AS "value",sort_value AS "sort_value",display_name AS "display_name",display_desc AS "display_desc",path AS "path",ipath AS "ipath",status AS "status",obj_status AS "obj_status",cr_date AS "cr_date",cr_uid AS "cr_uid",lu_date AS "lu_date",lu_uid AS "lu_uid" FROM categories_category AS tbl WHERE id IN (37,37,37,37,37,37,37,37,37,37,37,37,37,35,35,35,10004,10004,10004,37,37,37,37,37,37,10004)
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'sort_value' in 'field list'
````

**Comment by craigh** [comment] 2017-07-25 18:13
> use News after an upgrade. 

you must give more information on how to reproduce.

The news ticket says to view the main page. This works on my installation.

**Comment by rallek** [comment] 2017-07-25 18:37
I see this:
![grafik](https://user-images.githubusercontent.com/935250/28587925-0cb26760-7179-11e7-9252-7feebd271daa.png)
Next I will check if news is still up to date.

**Comment by rallek** [comment] 2017-07-25 18:44
I do have the latest News-master reinstalled. I see the same error message. Anything I can do to track down the issue?

**Comment by craigh** [comment] 2017-07-27 13:07
I cannot reproduce this. sent you an email.

remember to set `debug:true` in `custom_parameters.yml` and when there is an error it should give you much more information. What you have given here is not enough information to begin to solve the problem.

**Comment by craigh** [comment] 2017-07-27 13:34
ok, I pushed a chechen that may fix this (thanks to @Guite for the idea from his previous PR). I don't know exactly, but since the error is DBUtil, I'm guessing it is trying to use the old `tables.php` file. Try a newest build and see what happens.

**Comment by rallek** [comment] 2017-07-27 13:58
``debug: true`` should be set. Might be I have overwritten that setting during last upgrade loop.

**Comment by craigh** [comment] 2017-07-28 14:34
@rallek I tested this with your DB and it should work with most recent builds. closing (again). please test and confirm

**Comment by rallek** [comment] 2017-07-28 14:35
will test soon (waiting for next ci build)

**Closed by craigh** 2017-07-28 14:34 UTC
Labels: BC Break, Blocker

**Comment by rallek** [comment] 2017-07-28 15:19
fixed!
