### ISSUE TITLE
Zikula 3.0.4 fails to install on MYSQL 5.5

### ISSUE THREAD

**Issue by prbt2016** [zikula/core#4825] opened 2021-12-21 06:42 UTC
### Expected behaviour - What did you expect to happen?

Zikula 3.0.4 should be successfully installed on MYSQL 5.5

### Current behavior - What happened instead?

I was in the process of manual installation of Zikula 3.0.4 downloaded from official website, on CentOS Linux release 7.6.1810 (Core) with PHP 7.2.34, MYSQL 5.5.62, 2.2.34. However I get Internal server error while doing the same.

After entering the database details and admin details, when I click on 'Begin Install' following error is thrown after enabling debug mode via .env file i.e setting APP_ENV=dev and
APP_DEBUG=1 on hitting the following URL i.e : 

://{{DOMAIN.COM}}/zikula304/public/install/ajaxinstaller#installCard

Following is the error thrown via alert i.e :

```
Schema-Tool failed with Error 'An exception occurred while executing 'CREATE TABLE block_positions (pid INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, INDEX name_idx (name), PRIMARY KEY(pid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB':

SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.' while executing DDL: CREATE TABLE block_positions (pid INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, INDEX name_idx (name), PRIMARY KEY(pid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB (500 Internal Server Error)
```

### Steps to reproduce

```bash
1. Hit the install URL
2. Enter database details
3. Enter admin details
4. Click 'Begin Installer'
Above error is thrown.
```

### Zikula version

3.x-git

### PHP version

7.2.x

**Comment by Guite** [comment] 2021-12-21 07:30
Hi @prbt2016,
thanks for reporting!

The issue is fixed in 0a6f61b - 3.0.4 is to be re-released asap.

**Closed by Guite** 2021-12-21 07:30 UTC
Labels: Bug

**Comment by prbt2016** [comment] 2021-12-21 10:11
Thanks @Guite for looking into the issue so quickly. 
Kindly let me know when you re-release the 3.0.4 package.

**Comment by Guite** [comment] 2021-12-21 11:53
@prbt2016 the new release is available

**Comment by prbt2016** [comment] 2021-12-21 12:29
Hello @Guite ,

Thanks a lot for the new release of 3.0.4. It's working fine now.
