### ISSUE TITLE
[1.3.x] no theme translation

### ISSUE THREAD

**Issue by Portugao** [zikula/core#2635] opened 2015-11-06 10:37 UTC
It seems that there is an issue with the translation of themes.
If i put the needed language files into the theme folder locale i get no translations.
I tried all possible settings in the multilanguage part, no translations.

Not sure if it is really an issue or if i do something wrong.

**Comment by rallek** [comment] 2015-11-06 11:31
#2457 and #2459 may have the same root cause but they are 1.4.0 issues.

**Comment by craigh** [comment] 2015-11-06 12:39
@Portugao which Core version are you using?

**Comment by Portugao** [comment] 2015-11-06 13:01
Core version 1.3.10

**Comment by craigh** [comment] 2015-11-06 13:03
can you check if it worked correctly in Core-1.3.6 or less?

**Comment by Portugao** [comment] 2015-11-06 13:24
I will try.

**Comment by Portugao** [comment] 2015-11-06 14:53
First test with core version 1.3.5:
Same issue.
It seems, that there is a problem with the path to module templates....
For the footer.tpl in the directory 'includes' of the theme (anderas08) the translation does work.

**Comment by craigh** [comment] 2015-11-06 23:29
If you can figure out a fix, I would be happy to merge it.

**Comment by Portugao** [comment] 2015-11-07 10:44
Where i can find the relevant code?
Samstag, 07 November 2015, 00:29vorm. +0100 von Craig Heydenburg < notifications@github.com> :

**Comment by KratorD** [comment] 2016-02-23 07:16
Any fix / upgrade / work around for this ? @craigh  @Portugao

**Comment by Portugao** [comment] 2016-03-31 20:09
No, at the moment there is no idea where to find the relevant code....

**Comment by KratorD** [comment] 2016-04-01 06:43
Hello.
I'm testing with ZK 1.3.10 and custom theme. I'm using gettext from here http://zikula.org/gettext/
I'm traslating from spanish. It's working for me.
@Portugao Could you check your path, filenames, case sensitives...?

**Comment by Portugao** [comment] 2016-08-19 12:20
@KratorD What do mean with:

> Could you check your path, filenames, case sensitives...?

**Comment by Guite** [comment] 2017-08-05 11:41
Closing as there won't be a 1.3.13 release.

**Closed by Guite** 2017-08-05 11:41 UTC
Labels: Language/Translation
