### ISSUE TITLE
Zikula 1.4.4.build152 cannot load Scribite CKEditor

### ISSUE THREAD

**Issue by nmpetkov** [zikula/core#3227] opened 2016-11-29 12:14 UTC
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.4.build152
| PHP Version       | 5.6.24

### Expected behavior
Load CKEditor as in Zikula 1.4.3 without conflict

### Actual behavior
After installing Scribite module, CKEditor is not loaded if specified.

### Steps to reproduce
1. Install Zikula 1.4.4.build152
2. Install Scribite module (current state from Github, or tagged version 5.0.1).
3. Go to Blocks module, Hooks, and attach WYSIWYG editor hook.
4. Go to blocks list and edit HTML block.

### Comments
I tested to be sure same test in fresh install of Zikula 1.4.3, and editor loads successfully.
Then also fresh installed Zikula 1.4.4.build152, and did that several times with different versions of Scribite.
I found the problem is not in Scribite module, but in Zikula core, so I posted the issue here.
Below are pistures to ilustrate result in Zikula 1.4.3 and then in Zikula 1.4.4.build152.

**Zikula 1.4.3:**
![image](https://cloud.githubusercontent.com/assets/628801/20709376/9fe8ca94-b63d-11e6-8b08-40f25dcb3beb.png)

**Zikula 1.4.4.build152:**
![image](https://cloud.githubusercontent.com/assets/628801/20709389/b45f4822-b63d-11e6-8da8-bca61de601b5.png)

**Comment by Portugao** [comment] 2016-11-29 13:26
Can reproduce this with fresh install under php 5.6.25.

**Comment by craigh** [comment] 2016-11-29 21:17
This is a problem with the new asset combination feature. There is some incompatibility with Scribite.

if you set `zikula_asset_manager.combine: false` and then delete `app/cache/prod` the page works as expected.

when the feature is enabled, the page source doesn't appear to include all the required assets.

**Comment by craigh** [comment] 2016-11-29 22:39
basically, the problem is that when the assets are combined, the browser cannot find the `custconfig.js` file nor the `en.js` file. It looks like in former versions of the similar feature, this was also an issue and [handled here](https://github.com/zikula-modules/Scribite/blob/master/plugins/CKEditor/templates/editorheader.tpl#L3-L6) but including this file doesn't appear to solve the problem in this situation. I can change [this value](https://github.com/zikula-modules/Scribite/blob/master/plugins/CKEditor/templates/editorheader.tpl#L32) to `'{{$baseurl}}modules/Scribite/plugins/CKEditor/vendor/ckeditor/custconfig.js'` and that solves the problem for that file, but I cannot figure out the solution for the `en.js` file.

@Guite I'm hoping you can help here.

**Comment by Guite** [comment] 2016-11-30 06:13
Wouldn't it be possible to check if files exist before adding them to the merged file?

**Comment by craigh** [comment] 2016-11-30 10:12
probably, but that would break the site if required files were not included.

**Comment by craigh** [comment] 2016-11-30 10:55
The problem isn't that files *are* included. the problem is *how* they are included. The two files in question are included from within other scripts and I'm guessing the paths are relative and so the files are not found by the 'parent' script

this is all only for CKEditor. I imagine there would be problems with other editors as well.

**Comment by Guite** [comment] 2016-11-30 10:57
Another possible idea: maybe assets could be marked as "do not merge this". Would that help?
Or a simpler version: exclude all assets which contain *vendor* in their path?

**Comment by Guite** [comment] 2016-11-30 10:57
Also I wonder whether this problem does also exist for the old JS/CSS combination used in Smarty themes.

**Comment by craigh** [comment] 2016-11-30 10:58
did you read my post above?

> It looks like in former versions of the similar feature, this was also an issue

If you can please try some of your ideas.

**Comment by Guite** [comment] 2016-11-30 11:00
I have no time available this week. But imo this is not a release blocker, as the merger can just be disabled as a workaround.

**Comment by craigh** [comment] 2016-11-30 21:27
http://stackoverflow.com/questions/28500987/combine-ckeditor-into-1-file

http://stackoverflow.com/questions/15301099/ckeditor-4-build-minify-and-uglify/15305081#15305081

http://ckeditor.com/blog/CKEditor-Loading-performance-details

based on what I've read, I think we need to figure out a way to remove some files from the asset merger feature so that CKEditor is never combined. I don't see a way for it to work otherwise.

**Comment by craigh** [comment] 2016-11-30 21:30
https://dev.ckeditor.com/ticket/10961

**Comment by craigh** [comment] 2016-11-30 22:19
postponed to 1.4.5

**Comment by Guite** [comment] 2016-12-06 11:29
Fixed in https://github.com/zikula-modules/Scribite/commit/5eedf95140dea140ea207a6f06cbd886ee1603cf

**Closed by Guite** 2016-12-06 11:29 UTC
