### ISSUE TITLE
Was für ein Fehler bei Installieren Zikula 1.4

### ISSUE THREAD

**Issue by Alexalter** [zikula/core#2160] opened 2015-01-02 18:15 UTC
Fehler:
![zinsfehl](https://cloud.githubusercontent.com/assets/9826965/5598276/9cc8b1da-92b3-11e4-90d3-8f3a6b40418a.jpg)

bei anderen Hosting geht Zikula 1.4 einbahn frei zu Installieren, bei meinem nicht.

Grüß Alex

**Comment by rallek** [comment] 2015-01-02 18:19
dazu müssten wir die Unterschiede kennen ;-) /we should know the differences of both hoster

e.g. PHP-Version?

Aber warte noch etwas, der Installer wird gerade sowieso neu geschrieben/ Please wait some days. The installer will be rewritten anyway.

Gruß/Gratings
Ralf

**Comment by Alexalter** [comment] 2015-01-02 18:23
OK Danke!

**Comment by Guite** [comment] 2015-01-02 18:45
Welche PHP-Version hast Du auf diesem Server installiert? / Which PHP version do you have installed on this server?

**Comment by Alexalter** [comment] 2015-01-02 22:16
Sehe in Fehler Meldung, sonst 5.5 auch von allem Versionen installation ausprobiert.

**Comment by cmfcmf** [comment] 2015-01-06 21:39
refs https://github.com/symfony/symfony/pull/1042/files

**Comment by craigh** [comment] 2015-01-17 12:18
status on this? I can't understand the OP

**Comment by cmfcmf** [comment] 2015-01-17 18:40
@craigh He basically says he's able to install Zikula at other hosts, but on the current one it doesn't work and fails with the error above, regardless of his PHP version.

**Comment by craigh** [comment] 2015-01-17 18:41
If it works most places and doesn't work in one, surely it is a php config problem. no? This can't be a core issue, right?

**Comment by Guite** [comment] 2015-01-18 09:51
Seems like a Symfony problem:

http://forum.symfony-project.org/viewtopic.php?t=88300&p=190317
http://stackoverflow.com/questions/24995000/contexterrorexception-after-generating-a-bundle-in-symfony
http://www.cybertechquestions.com/installing-symfony2-on-synology-nas-51-home-server_1094543.html
https://www.google.com/search?q=ContextErrorException+ExecutableFinder+is_dir()

**Comment by craigh** [comment] 2015-01-18 14:12
I vote we close this as not core

**Comment by Guite** [comment] 2015-01-18 15:08
It seems to be caused by Assetic (at least assetic appears in the stack trace shown above).

**Comment by Guite** [comment] 2015-01-31 13:47
https://github.com/symfony/AsseticBundle/blob/master/DependencyInjection/AsseticExtension.php#L63
https://github.com/symfony/AsseticBundle/blob/master/DependencyInjection/Configuration.php#L67
this is where it seems to come from

Should we report this at https://github.com/symfony/AsseticBundle/issues ?
Maybe postpone to 1.4.1, too?

**Comment by Guite** [comment] 2015-01-31 13:56
Added a report at https://github.com/symfony/AsseticBundle/issues/348 , postponing this issue to 1.4.1

**Comment by craigh** [comment] 2015-04-11 19:26
@Alexalter why did you close this?

**Comment by craigh** [comment] 2015-04-11 20:02
now why did you reopen?

**Comment by Alexalter** [comment] 2015-04-12 07:15
Ich habe Host gewechselt zu all-inkl.com zikula 1.4.0 gut installiert und funktioniert.

**Comment by Alexalter** [comment] 2015-04-12 07:21
und brauche nun die Zikula 1.40 Deutsch

**Comment by cmfcmf** [comment] 2015-04-12 10:15
Hi @Alexalter, eine deutsche Übersetzung für Zikula 1.4 wird es wahrscheinlich geben, nachdem Zikula 1.4 endgültig veröffentlicht worden ist. Wenn es so weit ist, wird darüber dann sicherlich in einem News Beitrag auf http://support.zikula.de berichtet. Bis dahin musst du leider noch warten.
Lass dieses Ticket einfach offen, auch wenn bei dir jetzt alles funktioniert.

--------------
A German translation of Zikula 1.4 will be available shortly after the core is finally released. This ticket should be left open for now, until we get a response on the Assetic thing.

**Comment by Alexalter** [comment] 2015-04-12 11:32
OK Danke

**Comment by craigh** [comment] 2015-11-10 15:59
> A German translation of Zikula 1.4 will be available shortly after the core is finally released. This ticket should be left open for now, until we get a response on the Assetic thing.

Assetic seems not to care about this issue with not even a comment in over 10 months. I'm closing this issue. Please reopen if the issue is able to be reproduced.

**Closed by craigh** 2015-11-10 15:59 UTC
Labels: Install & Upgrade, Not core, Symfony

**Comment by rallek** [comment] 2015-11-10 16:07
Hi @Alexalter : We are currently installing the translation workflow in the German community /Wir richten gerade die Übersetzung in unserer Community ein.

**Comment by Alexalter** [comment] 2015-11-12 23:46
Cool
