### ISSUE TITLE
Theme preview doesn't use previewed theme's css?

### ISSUE THREAD

**Issue by robbrandt** [zikula/core#3999] opened 2019-12-13 23:05 UTC
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )

| Q                 | A
| ----------------- | ---
| Zikula Version    | 2.0.15
| PHP Version       | 5.6.x

## Expected Behavior
Following the steps laid out here:
https://github.com/zikula/core/blob/master/src/docs/Cookbook/ThemeExample.md
it should show the new theme when you click on the Preview link.

## Current Behavior
when I preview the new theme, it appears to be identical to the original BootstrapTheme.  Looking at the source code, it does appear to be using all resources of the NEW theme EXCEPT cerulean.css, which is still the original BootstrapTheme css.  I have properly set bootstrapPath: in theme.yml.

When I change the DEFAULT theme to be the new theme, it loads the correct cerulean.css.

## Steps to Reproduce
1. Do the tutorial
2. open the theme preview
3.Verify that the source is loading the original cerulean.css
4.change the default theme to the new theme
5.verify that the new cerulean.css is being loaded.

## Context
This has caused me to waste a lot of time thinking I am still loading the old theme rather than the new theme (which has no css changes so far, so looks identical).  LOL.

**Comment by Guite** [comment] 2019-12-14 08:33
Thanks for reporting.
Closing as duplicate of #3957 though.

**Closed by Guite** 2019-12-14 08:33 UTC
Labels: Bug
