### ISSUE TITLE
Make installer / upgrader error messages more verbose

### ISSUE THREAD

**Issue by cmfcmf** [zikula/core#2540] opened 2015-07-18 10:18 UTC
They already pop up in an alert if you install in dev / debug mode.

**Comment by Guite** [comment] 2016-11-12 14:31
This is about catching any PHP exceptions. Must be done both for CLI as well as Ajax mode.

**Comment by craigh** [comment] 2016-11-15 21:28
vote we move this to 1.4.5 and accidentally forget about it. 😝

**Comment by rallek** [comment] 2016-11-18 20:06
just implement #2204 than we are fine ;-)

**Comment by Guite** [comment] 2017-06-20 18:47
refs #3419

**Comment by Guite** [comment] 2020-01-31 18:31
Closing this issue, because we now use more reasonable defaults.
Of course there is still the possibility that problems occur, in these cases we need to investigate the causes.

**Closed by Guite** 2020-01-31 18:31 UTC
Labels: Core Install/Upgrade, Feature
