### ISSUE TITLE
ZAuthModule cannot edit admin user

### ISSUE THREAD

**Issue by Kaik** [zikula/core#2949] opened 2016-07-27 12:03 UTC
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.3
| PHP Version       | 5.6

### Expected behavior
Able to edit admin user without error.

### Actual behavior
Admin user throw
``` User names can contain letters, numbers, underscores, periods, spaces and/or dashes.
 The user name you entered is reserved. It cannot be used. ```
Admin name was not touched just email address.

### Steps to reproduce
go to domain/zauth/admin/list and edit user with uname admin

Related #2942

**Comment by craigh** [comment] 2016-07-27 12:06
what was the admin name?

**Comment by Kaik** [comment] 2016-07-27 12:10
Yes this one is admin name.

**Comment by craigh** [comment] 2016-07-27 12:31
I cannot reproduce. I just edited the admin email address with no difficulty.

**Comment by Kaik** [comment] 2016-07-27 12:32
I will not play around it is connected to #2942 When you install zikula you are asked to provide administrator account details please tell me how many people will choose ```admin``` ? and by the way, it does allow to install with this username. Second is that UsersModule by default creates or at least mention admin username here https://github.com/zikula/core/blob/1.4/src/system/UsersModule/UsersModuleInstaller.php#L224

Previously it worked that you could specify names you do not want users to register but as an administrator, you could use them or not. I think but I might be wrong but using ConstraintValidator in this case is not right solution.

**Comment by Kaik** [comment] 2016-07-27 12:32
> I cannot reproduce. I just edited the admin email address with no difficulty.

Is your admin uname equals ```admin``` ?

**Comment by craigh** [comment] 2016-07-27 12:34
why the anger? If I cannot reproduce, how can I fix it?

my admin name is not `admin` but `craig` which I selected on install.

**if** this is connected to #2942 then it is a duplicate ticket and should be closed as such.

**Comment by craigh** [comment] 2016-07-27 12:35
> Previously it worked that you could specify names you do not want users to register but as an administrator, you could use them or not.

this could be the issue. I think I eliminated the option for admins to use restricted names.

**Comment by Kaik** [comment] 2016-07-27 12:36
No anger at all... you are really reading me wrong I just want to help and make Zikula better. It might be that I cannot express my emotions by writing but when I'm angry I use angry people words to express that :)

**Comment by Kaik** [comment] 2016-07-27 13:35
Just to clear the air I have written my previous comment the one about playing before you asked about the name... I kind of expected that you are not using admin as administrator username. 
> if this is connected to #2942 then it is a duplicate ticket and should be closed as such.
The way it is connected to #2942 is not exactly same but relates to usage of ConstraintValidator I guess as the error is same... I do not know what is the "context" in which ConstraintValidator is working in #2942 is a different than the one in this ticket as in #2942 user entity is not edited it is just "selected" by name using DataTransformer http://symfony.com/doc/current/cookbook/form/data_transformers.html while in this ticket is just plain edit.

Yes,
``` I think I eliminated the option for admins to use restricted names.```
  yes.

**Comment by craigh** [comment] 2016-08-11 18:25
this is not yet actually fixed. working on it.

**Closed** 2016-08-11 19:08 UTC
Labels: Bug
