### ISSUE TITLE
Login always demands to accept site policies

### ISSUE THREAD

**Issue by rallek** [zikula/core#3351] opened 2016-12-31 13:00 UTC
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.5RC1
| PHP Version       | 5.5.30

### Expected behavior
There is nothing new to accept

### Actual behavior
![grafik](https://cloud.githubusercontent.com/assets/935250/21577594/f308875a-cf60-11e6-8aa1-79808481b3f7.png)

**allways** if a normal user logged in the user do get the above message. And there is no link to see what to accept.

see also #3345 

### Steps to reproduce
login with a normal user

**Comment by craigh** [comment] 2016-12-31 14:07
@Guite this might rather be a LegalModule ticket, but I can confirm this is a problem.

**Comment by Guite** [comment] 2016-12-31 14:17
I don't see this as a blocker for 1.4.5 though, as this problem has been existing in 1.4.4 as well.

**Comment by Guite** [comment] 2016-12-31 14:57
@rallek the policy links are correctly shown at my local test page. Maybe you don't see them due to a missing translation?

**Comment by Guite** [comment] 2016-12-31 15:12
Fixed in https://github.com/zikula-modules/Legal/commit/dc54a72c493ddb424e4534ef29576b4ff0568780

**Closed by Guite** 2016-12-31 15:12 UTC
Labels: Bug
