### ISSUE TITLE
cant get Block permissions to work on 1.4.3

### ISSUE THREAD

**Issue by MrMontesa** [zikula/core#3200] opened 2016-11-19 21:19 UTC
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.3
| PHP Version       | 5.6.26

### Expected behavior
Hide a block on welcome page for unregistered users.

### Actual behavior
Block is displayed

### Steps to reproduce
install zk1.4.3
create block for HTML and place in center position on welcome page. I use Andreas08 default theme 
Modul: ZikulaBlocksModule 
Type: HTML
add permission rule: 
Group: unregistered
Component: ZikulaBlocksModule:Main:
Instance: ::6 <- or whatever ID your block has
Level: no access

Can someone confirm that this is the correct strategy/approach? I'm at war with Permissions, so might be a wrong approach 😄 
Or can someone confirm that the above should work?
Thanks

**Comment by craigh** [comment] 2016-11-20 15:12
Share your entire permissions scheme. The order from top to bottom matters.

**Comment by MrMontesa** [comment] 2016-11-20 16:50
Here u go. Rule 31 & 32 should be the ones. The Block got the title "Hallo Mitglied" and has ID 6.
I tried various instance combinations like: `::6`, `:Hallo Mitglied:` or `:Hallo Mitglied:6`
The idea is to have a welcome HTML block for logged in club members.
![zk143_permissions](https://cloud.githubusercontent.com/assets/600125/20464558/6cf976ba-af49-11e6-83c6-b28ed2eef6fa.png)

**Comment by craigh** [comment] 2016-11-21 00:31
The permission rules information says you should be using the following:

![screen shot 2016-11-20 at 7 28 13 pm](https://cloud.githubusercontent.com/assets/350048/20467527/8ae074ea-af57-11e6-90b4-5c2a71f6ba18.png)

none of your examples seem to be using that, did you also try that? 

in your case:

Group: unregistered
Component: `HTMLblock::`
Instance: `Hallo Mitglied::`
Level: no access

**Comment by MrMontesa** [comment] 2016-11-21 07:31
As you can see from the screenshot I tried this with rule 33. The reason why I also tried :Main: was one of the suggestions by @Guite in another issue where component was documented differently in the "Help section" than it shoul de (ZikulaCategoriesModule).

To confirm I will give your suggestion another try and report back.

**Comment by MrMontesa** [comment] 2016-11-21 07:53
Ok,  tested your suggestion again and the block is still displayed.

I also did the permission checking on the bottom of the page for user `guest` which properly results in
 `Permission check result: guest: permission not granted` for rule 32 & 33.

**Comment by Guite** [comment] 2016-11-21 09:42
This is indeed a bug. The block content is correctly hidden, but the title is still visible.

**Comment by Guite** [comment] 2016-11-21 09:44
No good idea yet how to solve that. Maybe adding a dedicated block method which the theme system can use to determine visibility?

**Comment by craigh** [comment] 2016-11-21 10:23
> Ok, tested your suggestion again and the block is still displayed.

> The block content is correctly hidden, but the title is still visible.

so which is it?

**Comment by Guite** [comment] 2016-11-21 10:27
The block content is hidden due to https://github.com/zikula/core/blob/1.4/src/system/BlocksModule/Block/HtmlBlock.php#L30
But the actual block including it's title are still displayed. This decision is made outside of the block (theme system). But the theme system does not know the permission scheme. Hence my question about whether it makes sense to move the permission check into a dedicated block method (like `getPermissionCheck` or something) which the theme system can reuse.

**Comment by craigh** [comment] 2016-11-21 14:50
@MrMontesa please confirm that the problem is as @Guite describes it for you - the title is displayed but the content is hidden as expected.

Also - if possible confirm that other block types behave either properly or with the same problem.

**Comment by Guite** [comment] 2016-11-21 14:56
> please confirm that the problem is as @Guite describes it for you
I tested on his site, so I can confirm it, too :-)

**Comment by craigh** [comment] 2016-11-21 21:25
this is actually quite a complex problem.

The critical question is, "what component shall be in change of displaying a **_block title_**?"

possible answers:
 1. the block itself
 2. the blocks module
 3. the theme
 4. the user*

currently, the answer is (3) **the theme**. The block itself can control whether the content can be displayed, but not the title.

In my initial thought process, the block is only responsible for content and properties. The BlocksModule (not the block itself) creates the title and is therefore responsible for the content within the title. The theme is responsible for **displaying both together.**

changing this logic pattern would need some time and deeper thought.

an additional problem is that the HTML block (and Text block) do not have actual templates that are easily overridden, but this could be quite easily solved.

So - First, the premise of this ticket is wrong - permissions are working _as designed_ 😄 

Second, you can hide the title by setting the title as _blank_ and then creating a title in the content of the block (even use the `<h3>` tag) then use the settings I described above to hide as needed.

Third, we should add a template to the block I guess to make it easier to override...

Fourth - we can reconsider the logic flow but we would need time to do so, So I don't think that is in the scope of 1.4.4

*there is functionality in place to allow a user to hide block content using JS.

So, IMO this ticket is a **Feature request** and should be moved to 1.4.5

**Comment by craigh** [comment] 2016-11-21 21:41
hmm. In working out my solution locally, I've discovered that if you set the title to _empty_ then you can't use the title for a permission check.... duh. 👊

**Comment by Guite** [comment] 2016-11-22 05:50
also creating a title in the content of the block would only be possible for html and text blocks, but not for all other ones

**Comment by MrMontesa** [comment] 2016-11-22 05:56
From user perspective I have to disagree with Craigh. Theres a feature offered by the core which does not work as expected. Thus it's a bug. 
The fact that there might be workaround in some cases may lower the priorities to get it fixed but it remains a bug. 
Also grow use-case point of view seems to be a quite common idea,right? Having a welcome screen for user that just logged in. 
I'm happy to support you guys as best as I can in order to get this fixed.

**Comment by Guite** [comment] 2016-11-22 06:00
Here are two different proposals for possible solution approaches:

1. Introduce some logic like `only if (block has any content) displayTheBlock`
2. Move permission check into a separate method (e.g. `isVisible($properties)`) which can be called by `display` but also by the theme system

**Comment by craigh** [comment] 2016-11-23 13:35
Fixed with @Guite 's first suggestion. please test.

**Closed** 2016-11-23 13:34 UTC
Labels: Bug, Discussion

**Comment by MrMontesa** [comment] 2016-11-24 10:32
Tested with zk1.4.4-build144 and can confirm that it is working smoothly.
Thanks a lot for the swift turn around.
