### ISSUE TITLE
cannot declare interface Stringable, because the name is already in use

### ISSUE THREAD

**Issue by rallek** [zikula/core#4414] opened 2020-07-20 18:27 UTC
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )

| Q                 | A
| ----------------- | ---
| Zikula Version    | 3.0.0
| PHP Version       | 7.4.5 (and 7.1 tested)

## Expected Behavior

no errormessage

## Current Behavior

In multilingual setting and some modules installed (News, Content, MediaModule, Scribite!). If I now want to open `Main Settings` I do get the following error:

```
Symfony\Component\ErrorHandler\Error\FatalError:
Error: Cannot declare interface Stringable, because the name is already in use

  at vendor/symfony/polyfill-php80/Resources/stubs/Stringable.php:7   
```

**Comment by craigh** [comment] 2020-07-20 21:20
My guess here is that MediaModule or Content is requiring symfony/polyfill-php80 and of course so does the core and so they conflict.

a workaround could be do delete the `/vendor/symfony/polyfill-php80` directory inside MediaModule or Content and see if that solves the problem.

this is why it is dangerous for not-required modules to require the same things as the core

**Comment by Guite** [comment] 2020-07-21 04:18
Media does require `symfony/polyfill-php80`.

> this is why it is dangerous for not-required modules to require the same things as the core

The problem is that often such dependencies are transitive.
In this example:

`media-module -> james-heinrich/getid3 -> php-http/cache-plugin -> symfony/polyfill-php80`

A real solution would be #3438 but that is of course not possible for 3.0.x.

**Comment by Guite** [comment] 2020-07-21 04:20
@rallek temporary workaround: open `src/extensions/cmfcmf/media-module/vendor/symfony/polyfill-php80/Resources/stubs/Stringable.php` and remove everything except `<?php`.

**Comment by craigh** [comment] 2020-07-21 12:58
why not?

> a workaround could be do delete the /vendor/symfony/polyfill-php80 directory inside MediaModule

deleting the entire dir seems like it shouldn't matter. The vendor is available in the core.

**Comment by craigh** [comment] 2020-12-30 14:00
closed in favor of https://github.com/zikula-modules/MediaModule/issues/239

**Closed by craigh** 2020-12-30 14:00 UTC
Labels: Bug
