### ISSUE TITLE
Whitelist translations 

### ISSUE THREAD

**Issue by cmfcmf** [zikula/core#2541] opened 2015-07-18 15:45 UTC
Refs https://github.com/zikula-modules/Multisites/issues/17

**Comment by craigh** [comment] 2017-04-06 22:42
@Guite how important is this? Should we implement this feature or delay to 2.1.0?

**Comment by Guite** [comment] 2017-04-07 05:10
Can wait until 2.1.0 I think.

**Comment by Guite** [comment] 2017-08-22 15:26
Closed as duplicate of https://github.com/zikula/core/issues/3781  (which describes more concretely what to do)

**Closed by Guite** 2017-08-22 15:26 UTC
Labels: Feature, Language/Translation
