### ISSUE TITLE
saving user after edit gives: The &dollar;user record or the UID is invalid or the UID does not match.

### ISSUE THREAD

**Issue by MrMontesa** [zikula/core#3103] opened 2016-10-04 13:13 UTC
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.3
| PHP Version       | 5.6.25

### Expected behavior
Editing a user should be possible.

### Actual behavior
When editing an existing user (add/remove group memebership) and clicking on save, Zikula exists with error message. Heres the Stack Trace:

```
in lib/Zikula/Core/Exception/FatalErrorException.php at line 30   -
     * @param string $filename
     * @param int $lineno
     */
    public function __construct($message = 'Fatal Error!', $code = 0, $severity = 1, $filename = __FILE__, $lineno = __LINE__)
    {
        parent::__construct($message, $code, $severity, $filename, $lineno);
    }
at UsersUiListener ->validateEdit (object(GenericEvent), 'module.users.ui.validate_edit.modify_user', object(TraceableEventDispatcher)) 
at call_user_func (array(object(UsersUiListener), 'validateEdit'), object(GenericEvent), 'module.users.ui.validate_edit.modify_user', object(TraceableEventDispatcher)) 
in vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php at line 61   + 
at WrappedListener ->__invoke (object(GenericEvent), 'module.users.ui.validate_edit.modify_user', object(Zikula_EventManager)) 
at call_user_func (object(WrappedListener), object(GenericEvent), 'module.users.ui.validate_edit.modify_user', object(Zikula_EventManager)) 
in vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php at line 184   + 
at EventDispatcher ->doDispatch (array(object(WrappedListener), object(WrappedListener)), 'module.users.ui.validate_edit.modify_user', object(GenericEvent)) 
in vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php at line 46   + 
at EventDispatcher ->dispatch ('module.users.ui.validate_edit.modify_user', object(GenericEvent), null) 
in lib/legacy/Zikula/EventManager.php at line 95   + 
at Zikula_EventManager ->dispatch ('module.users.ui.validate_edit.modify_user', object(GenericEvent)) 
in vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php at line 140   + 
at TraceableEventDispatcher ->dispatch ('module.users.ui.validate_edit.modify_user', object(GenericEvent)) 
in system/UsersModule/Controller/UserAdministrationController.php at line 146   + 
at UserAdministrationController ->modifyAction (object(Zikula_Request_Http), object(UserEntity)) 
at call_user_func_array (array(object(UserAdministrationController), 'modifyAction'), array(object(Zikula_Request_Http), object(UserEntity))) 
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php at line 144   + 
at HttpKernel ->handleRaw (object(Zikula_Request_Http), '1') 
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php at line 64   + 
at HttpKernel ->handle (object(Zikula_Request_Http), '1', true) 
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php at line 69   + 
at ContainerAwareHttpKernel ->handle (object(Zikula_Request_Http), '1', true) 
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php at line 185   + 
at Kernel ->handle (object(Zikula_Request_Http)) 
in index.php at line 23   + 
```

### Steps to reproduce
- Install Zikula
- Add new group
- Add user to new group
- save

**Comment by craigh** [comment] 2016-10-05 22:21
> When editing an existing user

changing a user's group assignments and editing a user are two different things. I assume you mean that the problem is with group assignments?

**Comment by MrMontesa** [comment] 2016-10-06 06:43
Hey Craigh,
sorry for not being presize enough. I'm oon /users/admin/user/modify/3. Any change results into the error message above.
I initially recognized it when adding another group to that user via that page. But I also receive the error when adding a _UREALNAME for example.
What I also just recognized is that I'm immediately logged off after receiving that error message. I have to re-login to continue.

**Comment by craigh** [comment] 2016-10-06 19:31
I cannot reproduce this behavior with 1.4.4. Can you install and test the issue there?

**Comment by MrMontesa** [comment] 2016-10-07 10:03
Hey Craigh,
I did a bit more testing and can reproduce the issue in 1.4.4 as well. Since the page looked much different in 1.4.4 testbed than the other page I recognized that Legal and Profile module were installed too.

In fact as soon as I install Legal and the Legal module content is displayed withing the user/edit page, the error appears again.
Hope this helps to reproduce.

**Comment by craigh** [comment] 2016-10-07 13:03
so the problem is with Legal then. @Guite

**Comment by Guite** [comment] 2016-10-21 14:22
Fixed in https://github.com/zikula-modules/Legal/commit/8f066a31246482d085a62b58590a25a7faa6c5df

**Closed by Guite** 2016-10-21 14:22 UTC
Labels: Bug
