### ISSUE TITLE
Set up mail service on install

### ISSUE THREAD

**Issue by craigh** [zikula/core#3052] opened 2016-08-29 10:21 UTC
| Q | A |
| --- | --- |
| Zikula Version | 1.4.3-rc2 |
| PHP Version | 5.6.24-1+deb.sury.org~xenial+1 |

Perhaps the installer should attempt to set up the mail service or at least notify the admin that the mail service requires set up.

**Comment by craigh** [comment] 2016-08-29 10:42
additionally, if the email server is not setup it should be handled better than a 500 - this was after attempting to register with the email service not properly set up

![screen_shot_2016-08-28_at_11 58 46_am](https://cloud.githubusercontent.com/assets/350048/18049032/b79990c4-6db3-11e6-8a34-48cf0b1189ca.png)

**Comment by MrMontesa** [comment] 2016-10-04 11:12
I just stumbeld upon this issue since I'm not able to get mailing feature to work.
In case mailing cant be setup during installation process I would recommend to set it to "DEV - no mailing" and highlight this with an info window in admin area.

**Comment by Guite** [comment] 2016-11-09 10:21
The problem about the 500 error has already been fixed in 5872d6c545dc6ebbc2ccef9b4502350d74ea89e2

**Comment by Guite** [comment] 2016-11-09 10:22
Any proposal about the actual feature request: how should the installer do that? Adding an additional step offering mail configuration options to setup after the user entered his admin credentials?

**Comment by MrMontesa** [comment] 2016-11-09 12:19
From end-user perspective I would propose the follwing:
- no Zikula function, setting change, etc should end in a 500 and break the system.
- On install, set the mail feature to "DEV - no mail"
- In admin area display an info windows as long as mailing feature is disabled. Same like "There is a new Zikula version available"
- The info windows should contain a direct link into the mail config area to change the settings

**Comment by craigh** [comment] 2016-11-12 10:38
> Perhaps the installer should attempt to set up the mail service or at least notify the admin that the mail service requires set up.

I think the installer should *try* to set up the mailer on its own first. Maybe it can try several methods and see if they are available somehow.

I do not think the mailer should be disabled or set to DEV on install. This will mean the product is not functional "out of the box" and this will only lead to support requests.

If it determined (somehow) that the mail service cannot be set up/enabled, then a notice should be set in the admin panel with a link as @MrMontesa suggested.

**Comment by nmpetkov** [comment] 2016-11-12 13:47
I hope this issue is right place to write the problem I have. I attempt to send test email from mailer module and get:
``` It looks like the message could not be sent properly. ```
and the mail is not sent.

Please point me how to change  configuration to be able to send test mail.

- It is Zikula 1.4.4.build100 fresh install
- I **RECEIVE** confirmation email after Zikula installation.
- Configuration is as after installation:

![image](https://cloud.githubusercontent.com/assets/628801/20238200/7ddd9260-a8ee-11e6-97f8-3306f91f42bf.png)

**Comment by Guite** [comment] 2016-11-12 14:13
@nmpetkov we had problems with that because of `delivery_addresses`. This was #2889 which has been fixed by a custom yaml dumper in #2926. Please check if your `dynamic/generated.yml` file contains `delivery_addresses: []` or `delivery_addresses: { }`. It should use the square brackets.

Beside this I also have problems with sending mails in my local test environment. I couldn't track it down yet though.

**Comment by nmpetkov** [comment] 2016-11-12 14:23
@Guite Yes, I checked this before to write, they are square brackets (it is fresh install of current files from GitHub - Zikula 1.4.4.build100):
![image](https://cloud.githubusercontent.com/assets/628801/20238432/1ed10b8e-a8f4-11e6-8b14-97a375f04987.png)

**Comment by nmpetkov** [comment] 2016-11-12 17:02
After debugging I found the problem, and it seems is not connected to this issue. If so, I can move postings to other issue.

**This is working without error**: When fulfil test mail form, if ```Recipient's name``` contains only ASCII characters, then test mail is sent properly.

**NOT WORKING**: In some cases when using other UTF-8 characters (for example my names in Cyrillic), then test mail is not sent. More particulars:

Swift-mailer puts strange to me formatting (I echoed just before the line with call to php mail() function in file ```/home/cmstory/public_html/zktest/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/SimpleMailInvoker.php```:

![image](https://cloud.githubusercontent.com/assets/628801/20239359/3b69a4aa-a907-11e6-8825-f5e12b42c946.png)

It is also possible php mail() function to fail in sending some names, or is mail header problem.

**Comment by nmpetkov** [comment] 2016-11-12 17:54
And addition to above:
Same test in Zikula 1.3.10 work well, no problem to send test mail with any sender name - I used same name as in previous posting here, to compare.
Also looked - in Zikula 1.3.10 is used other mailer class (not SuiftMailer), and that means the problem is not in php mail() function, but encoding of strings or generated header in Zikula 1.4 SuiftMailer.

**Comment by craigh** [comment] 2016-11-13 23:07
> I hope this issue is right place to write the problem I have

@nmpetkov  I think it would be better if you created a new ticket for your issue. A bug with the current setup is different than the purpose of the ticket. Please do so and copy this information to your new ticket, then delete the comments here. thanks.

**Closed** 2020-03-29 17:50 UTC
Labels: Core Install/Upgrade, Documentation, Feature
