### ISSUE TITLE
Zikula 2.0.1 Categories not worked

### ISSUE THREAD

**Issue by AlexL777** [zikula/core#3817] opened 2017-09-22 09:24 UTC
| Q                 | A
| ----------------- | ---
| Zikula Version    | 2.0.1
| PHP Version       | 7.1

### Expected behavior
Zikula 2.0.1 Categories can not be edited or create new ones.

### Actual behavior
I tried to edit an already existing category and a message with 500 Error is displayed. In the Console of the Chrome browser I see this error message.

`Failed to load resource: the server responded with a status of 500 () contextMenu/edit/34 `

Can you confirm this and it is possibly still a bug.

Thanks in advance.

**Comment by shefik** [comment] 2017-09-22 09:56
Duplicate of https://github.com/zikula/core/issues/3807

**Closed** 2017-09-22 10:04 UTC
