### ISSUE TITLE
adding permission is failing

### ISSUE THREAD

**Issue by rallek** [zikula/core#3809] opened 2017-09-17 15:31 UTC
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.5.1
| PHP Version       | 5.6

### Expected behavior
adding a prmission the modal window should appear

### Actual behavior
modal window do not appear. The cross is turning all the time.

### Steps to reproduce
I just upgraded my site from 1.5.0 to 1.5.1 in a copy. The original site is still 1.5.0. There It is no problem.
If you click at the link to add a permission the problem is showing up

**Comment by Guite** [comment] 2017-09-17 15:32
Please check your browser's console whether an error is shown there. Maybe this is a duplicate of #3807 ?

**Comment by rallek** [comment] 2017-09-17 16:03
indeed there is an error:
``Error: The route "zikulapermissionsmodule_permission_edit" does not exist.``

**Comment by rallek** [comment] 2017-09-17 18:25
deleting the file in ``web/js`` is helping

**Comment by Guite** [comment] 2017-09-17 18:35
Closed as dup of #3807

**Closed by Guite** 2017-09-17 18:35 UTC
