### ISSUE TITLE
Fatal Error: Two extensions share the same displayname. [%ext1%] and [%ext2%]

### ISSUE THREAD

**Issue by robbrandt** [zikula/core#3005] opened 2016-08-20 00:17 UTC
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.3 build 135
| PHP Version       | 5.5.26

### Expected behavior
Display Extensions page without error

### Actual behavior
Error 500 
Fatal Error: Two extensions share the same displayname. [%ext1%] and [%ext2%]

### Steps to reproduce
Take an existing 1.3.x site and upgrade it to 1.4.3, strictly by the upgrade instructions.

However the upgrade instructions make no mention of deleting modules/Profile and module/Legal, which are replaced in 1.4.3 core.

**Comment by robbrandt** [comment] 2016-08-20 00:18
Also, the error message is trying to show which modules have the same name, but fails to do so.

**Comment by Guite** [comment] 2016-08-20 05:55
I've fixed the error message in cde69277db8b9b20004f09936f49037833125b17
About the original problem @craigh should advice how to handle that. Maybe it is enough to add a note to the upgrade instructions, but I don't know about this.

**Comment by craigh** [comment] 2016-08-20 12:16
> However the upgrade instructions make no mention of deleting modules/Profile and module/Legal, which are replaced in 1.4.3 core.

It is not clear to me if you first followed the instructions to remove **all files** and then placed the Core-1.4.3 files in place (which includes profile and legal) or if you did something else.

> Take an existing 1.3.x site

I assume also that this is a formerly _operational_ site, meaning you have several modules installed, apparently including profile and legal?

**Comment by craigh** [comment] 2016-08-20 12:36
OK - I cannot reproduce this :(

I am using PHP 5.5.26 also

I installed Core-1.3.10 and ensured that both Profile and Legal are installed.
I then upgraded this core to 1.4.3 (build 142) with no errors.

please provide a dump of your `modules` table from the **pre-upgraded** database.

**Comment by robbrandt** [comment] 2016-08-20 17:49
Yes, I removed all files, completely.  This step in the instructions is where they reappeared:

  - copy from your backup ``/userdata``, ``/modules`` and your theme to your new upload. The folders of your modules and themes should be at the exact same place like your backup.

I was more focused on following the directions than actually THINKING about what I was doing, so it didn't occur to me to remove the old Profile and Legal modules before copying them back into the new installation along with all my other modules.  As soon as I saw the error I knew exactly which ones were the culprits.

**Comment by robbrandt** [comment] 2016-08-20 17:53
Here's the 1.3.10 module dump:

INSERT INTO `modules` (`id`, `name`, `type`, `displayname`, `url`, `description`, `directory`, `version`, `capabilities`, `state`, `securityschema`, `core_min`, `core_max`) VALUES
(2, 'Admin', 3, 'Administration panel', 'adminpanel', 'Backend administration interface.', 'Admin', '1.9.1', 'a:1:{s:5:"admin";a:1:{s:7:"version";s:3:"1.0";}}', 3, 'a:1:{s:7:"Admin::";s:38:"Admin Category name::Admin Category ID";}', '', ''),
(29, 'BadBehavior', 2, 'BadBehavior', 'badbehavior', 'BadBehavior', 'BadBehavior', '2.0.43', 'a:1:{s:5:"admin";a:1:{s:7:"version";s:3:"1.0";}}', 3, 'a:2:{s:13:"BadBehavior::";s:2:"::";s:17:"BadBehavior:User:";s:10:"UserName::";}', '1.3.0', ''),
(3, 'Blocks', 3, 'Blocks', 'blocks', 'Block administration module.', 'Blocks', '3.8.2', 'a:3:{s:15:"hook_subscriber";a:1:{s:7:"enabled";b:1;}s:5:"admin";a:1:{s:7:"version";s:3:"1.0";}s:4:"user";a:1:{s:7:"version";s:3:"1.0";}}', 3, 'a:4:{s:8:"Blocks::";s:30:"Block key:Block title:Block ID";s:16:"Blocks::position";s:26:"Position name::Position ID";s:23:"Menutree:menutreeblock:";s:26:"Block ID:Link Name:Link ID";s:19:"ExtendedMenublock::";s:17:"Block ID:Link ID:";}', '', ''),
(17, 'Captcha', 2, 'Captcha', 'captcha', 'Captcha hook module', 'Captcha', '1.0.0', 'a:2:{s:13:"hook_provider";a:1:{s:7:"enabled";b:1;}s:5:"admin";a:1:{s:7:"version";s:3:"1.0";}}', 3, 'a:1:{s:9:"Captcha::";s:2:"::";}', '1.3.0', ''),
(4, 'Categories', 3, 'Categories', 'categories', 'Category administration.', 'Categories', '1.2.1', 'a:2:{s:5:"admin";a:1:{s:7:"version";s:3:"1.0";}s:4:"user";a:1:{s:7:"version";s:3:"1.0";}}', 3, 'a:1:{s:20:"Categories::Category";s:40:"Category ID:Category Path:Category IPath";}', '', ''),
(26, 'Clip', 2, 'Clip', 'clip', 'Dynamic content publishing platform for Zikula.', 'Clip', '0.9.2', 'a:3:{s:15:"hook_subscriber";a:2:{s:7:"enabled";b:1;s:13:"subscribe_own";b:1;}s:5:"admin";a:1:{s:7:"version";s:3:"1.0";}s:4:"user";a:1:{s:7:"version";s:3:"1.0";}}', 3, 'a:5:{s:6:"Clip::";s:2:"::";s:21:"Clip:grouptypeid:main";s:15:"tid::templateid";s:21:"Clip:grouptypeid:list";s:15:"tid::templateid";s:24:"Clip:grouptypeid:display";s:18:"tid:pid:templateid";s:21:"Clip:grouptypeid:edit";s:21:"tid:pid:workflowstate";}', '1.3.2', '1.3.99'),
(19, 'Content', 2, 'Content editing', 'content', 'Content is a page editing module. With it you can insert and edit various content items, such as HTML texts, videos, Google maps and much more.', 'Content', '4.0.1', 'a:3:{s:15:"hook_subscriber";a:1:{s:7:"enabled";b:1;}s:5:"admin";a:1:{s:7:"version";s:3:"1.0";}s:4:"user";a:1:{s:7:"version";s:3:"1.0";}}', 3, 'a:4:{s:9:"Content::";s:2:"::";s:22:"Content:plugins:layout";s:13:"Layout name::";s:23:"Content:plugins:content";s:19:"Content type name::";s:13:"Content:page:";s:9:"Page id::";}', '1.3.0', '1.3.99'),
(5, 'Errors', 3, 'Errors', 'errors', 'Error display module.', 'Errors', '1.1.1', 'a:1:{s:4:"user";a:1:{s:7:"version";s:3:"1.0";}}', 3, 'a:1:{s:8:"Errors::";s:2:"::";}', '', ''),
(1, 'Extensions', 3, 'Extensions', 'extensions', 'Manage your modules and plugins.', 'Extensions', '3.7.10', 'a:1:{s:5:"admin";a:1:{s:7:"version";s:3:"1.0";}}', 3, 'a:1:{s:12:"Extensions::";s:2:"::";}', '', ''),
(20, 'EZComments', 2, 'Comments', 'comments', 'Attach comments to every kind of content using hooks', 'EZComments', '3.0.0', 'a:4:{s:13:"hook_provider";a:1:{s:7:"enabled";b:1;}s:15:"hook_subscriber";a:1:{s:7:"enabled";b:1;}s:5:"admin";a:1:{s:7:"version";s:3:"1.0";}s:4:"user";a:1:{s:7:"version";s:3:"1.0";}}', 3, 'a:3:{s:12:"EZComments::";s:25:"Module:Item ID:Comment ID";s:21:"EZComments::trackback";s:15:"Module:Item ID:";s:20:"EZComments::pingback";s:15:"Module:Item ID:";}', '1.3.0', ''),
(21, 'FAQ', 2, 'FAQ', 'faq', 'Frequently Asked Questions', 'FAQ', '2.3.2', 'a:3:{s:15:"hook_subscriber";a:1:{s:7:"enabled";b:1;}s:5:"admin";a:1:{s:7:"version";s:3:"1.0";}s:4:"user";a:1:{s:7:"version";s:3:"1.0";}}', 3, 'a:1:{s:5:"FAQ::";s:8:"FAQ ID::";}', '', ''),
(27, 'Files', 2, 'File Manager', 'files', 'File manager for Zikula sites.', 'Files', '1.0.0', 'a:2:{s:5:"admin";a:1:{s:7:"version";s:3:"1.0";}s:4:"user";a:1:{s:7:"version";s:3:"1.0";}}', 3, 'a:1:{s:7:"Files::";s:2:"::";}', '1.3.0', '1.3.99'),
(6, 'Groups', 3, 'Groups', 'groups', 'User group administration module.', 'Groups', '2.3.2', 'a:2:{s:5:"admin";a:1:{s:7:"version";s:3:"1.0";}s:4:"user";a:1:{s:7:"version";s:3:"1.0";}}', 3, 'a:1:{s:8:"Groups::";s:10:"Group ID::";}', '', ''),
(15, 'Legal', 2, 'Legal info manager', 'legalmod', 'Provides an interface for managing the site''s legal documents.', 'Legal', '2.0.1', 'a:2:{s:5:"admin";a:1:{s:7:"version";s:3:"1.0";}s:4:"user";a:1:{s:7:"version";s:3:"1.0";}}', 3, 'a:8:{s:7:"Legal::";s:2:"::";s:18:"Legal::legalnotice";s:2:"::";s:17:"Legal::termsofuse";s:2:"::";s:20:"Legal::privacypolicy";s:2:"::";s:16:"Legal::agepolicy";s:2:"::";s:29:"Legal::accessibilitystatement";s:2:"::";s:30:"Legal::cancellationrightpolicy";s:2:"::";s:22:"Legal::tradeconditions";s:2:"::";}', '1.3.0', '1.3.99'),
(7, 'Mailer', 3, 'Mailer', 'mailer', 'Mailer module, provides mail API and mail setting administration.', 'Mailer', '1.3.2', 'a:1:{s:5:"admin";a:1:{s:7:"version";s:3:"1.0";}}', 3, 'a:1:{s:8:"Mailer::";s:2:"::";}', '', ''),
(22, 'News', 2, 'News publisher', 'news', 'Provides the ability to publish and manage news articles contributed by site users, with support for news categories and various associated blocks.', 'News', '3.0.0', 'a:3:{s:15:"hook_subscriber";a:1:{s:7:"enabled";b:1;}s:5:"admin";a:1:{s:7:"version";s:3:"1.0";}s:4:"user";a:1:{s:7:"version";s:3:"1.0";}}', 3, 'a:3:{s:6:"News::";s:26:"Contributor ID::Article ID";s:19:"News:pictureupload:";s:2:"::";s:24:"News:publicationdetails:";s:2:"::";}', '1.3.0', ''),
(8, 'PageLock', 3, 'Page lock', 'pagelock', 'Provides the ability to lock pages when they are in use, for content and access control.', 'PageLock', '1.1.1', 'a:0:{}', 1, 'a:1:{s:10:"PageLock::";s:2:"::";}', '', ''),
(9, 'Permissions', 3, 'Permissions', 'permissions', 'User permissions manager.', 'Permissions', '1.1.1', 'a:1:{s:5:"admin";a:1:{s:7:"version";s:3:"1.0";}}', 3, 'a:1:{s:13:"Permissions::";s:2:"::";}', '', ''),
(23, 'PostCalendar', 2, 'PostCalendar', 'postcalendar', 'Calendar for Zikula', 'PostCalendar', '8.0.0', 'a:4:{s:13:"hook_provider";a:1:{s:7:"enabled";b:1;}s:15:"hook_subscriber";a:1:{s:7:"enabled";b:1;}s:5:"admin";a:1:{s:7:"version";s:3:"1.0";}s:4:"user";a:1:{s:7:"version";s:3:"1.0";}}', 3, 'a:2:{s:19:"PostCalendar::Event";s:21:"Event Title::Event ID";s:14:"PostCalendar::";s:2:"::";}', '1.3.3', '1.3.99'),
(16, 'Profile', 2, 'Profile', 'profile', 'Provides a personal account control panel for each registered user, an interface to administer the personal information items displayed within it, and a registered users list functionality. Works in close unison with the ''Users'' module.', 'Profile', '1.6.1', 'a:3:{s:7:"profile";a:1:{s:7:"version";s:3:"1.0";}s:5:"admin";a:1:{s:7:"version";s:3:"1.0";}s:4:"user";a:1:{s:7:"version";s:3:"1.0";}}', 3, 'a:6:{s:9:"Profile::";s:2:"::";s:13:"Profile::view";s:2:"::";s:13:"Profile::item";s:56:"DynamicUserData PropertyName::DynamicUserData PropertyID";s:16:"Profile:Members:";s:2:"::";s:22:"Profile:Members:recent";s:2:"::";s:22:"Profile:Members:online";s:2:"::";}', '1.3.0', '1.3.99'),
(24, 'Scribite', 2, 'Scribite', 'scribite', 'WYSIWYG for Zikula', 'Scribite', '4.3.0', 'a:1:{s:5:"admin";a:1:{s:7:"version";s:3:"1.0";}}', 3, 'a:1:{s:10:"Scribite::";s:12:"Modulename::";}', '1.3.0', '1.3.99'),
(10, 'Search', 3, 'Site search', 'search', 'Site search module.', 'Search', '1.5.2', 'a:2:{s:5:"admin";a:1:{s:7:"version";s:3:"1.0";}s:4:"user";a:1:{s:7:"version";s:3:"1.0";}}', 3, 'a:1:{s:8:"Search::";s:13:"Module name::";}', '', ''),
(11, 'SecurityCenter', 3, 'Security Center', 'securitycenter', 'Manage site security and settings.', 'SecurityCenter', '1.4.4', 'a:1:{s:5:"admin";a:1:{s:7:"version";s:3:"1.0";}}', 3, 'a:1:{s:16:"SecurityCenter::";s:2:"::";}', '', ''),
(12, 'Settings', 3, 'General settings', 'settings', 'General site configuration interface.', 'Settings', '2.9.7', 'a:1:{s:5:"admin";a:1:{s:7:"version";s:3:"1.0";}}', 3, 'a:1:{s:10:"Settings::";s:2:"::";}', '', ''),
(28, 'SurveyManager', 2, 'Survey manager', 'surveymanager', 'Flexible surveyor.', 'SurveyManager', '2.0.0', 'a:3:{s:15:"hook_subscriber";a:1:{s:7:"enabled";b:1;}s:5:"admin";a:1:{s:7:"version";s:3:"1.0";}s:4:"user";a:1:{s:7:"version";s:3:"1.0";}}', 3, 'a:13:{s:15:"SurveyManager::";s:2:"::";s:19:"SurveyManager::Ajax";s:2:"::";s:28:"SurveyManager:ItemListBlock:";s:13:"Block title::";s:21:"SurveyManager:Survey:";s:11:"Survey ID::";s:19:"SurveyManager:Page:";s:9:"Page ID::";s:25:"SurveyManager:Survey:Page";s:18:"Survey ID:Page ID:";s:23:"SurveyManager:Question:";s:13:"Question ID::";s:27:"SurveyManager:Page:Question";s:20:"Page ID:Question ID:";s:23:"SurveyManager:Response:";s:13:"Response ID::";s:29:"SurveyManager:Survey:Response";s:22:"Survey ID:Response ID:";s:27:"SurveyManager:ResponseData:";s:17:"ResponseData ID::";s:35:"SurveyManager:Response:ResponseData";s:28:"Response ID:ResponseData ID:";s:35:"SurveyManager:Question:ResponseData";s:28:"Question ID:ResponseData ID:";}', '1.3.5', '1.3.99'),
(25, 'Tag', 2, 'Tag', 'tag', 'Tagging module', 'Tag', '1.0.2', 'a:3:{s:13:"hook_provider";a:1:{s:7:"enabled";b:1;}s:5:"admin";a:1:{s:7:"version";s:3:"1.0";}s:4:"user";a:1:{s:7:"version";s:3:"1.0";}}', 3, 'a:1:{s:5:"Tag::";s:2:"::";}', '1.3.2', '1.3.99'),
(13, 'Theme', 3, 'Themes', 'theme', 'Themes module to manage site layout, render and cache settings.', 'Theme', '3.4.2', 'a:2:{s:5:"admin";a:1:{s:7:"version";s:3:"1.0";}s:4:"user";a:1:{s:7:"version";s:3:"1.0";}}', 3, 'a:1:{s:7:"Theme::";s:12:"Theme name::";}', '', ''),
(14, 'Users', 3, 'Users', 'users', 'Provides an interface for configuring and administering registered user accounts. Incorporates all needed functionality, but can work in close unison with the third party profile module configured in the general settings of the site.', 'Users', '2.2.0', 'a:4:{s:14:"authentication";a:1:{s:7:"version";s:3:"1.0";}s:15:"hook_subscriber";a:1:{s:7:"enabled";b:1;}s:5:"admin";a:1:{s:7:"version";s:3:"1.0";}s:4:"user";a:1:{s:7:"version";s:3:"1.0";}}', 3, 'a:2:{s:7:"Users::";s:14:"Uname::User ID";s:16:"Users::MailUsers";s:2:"::";}', '1.3.0', '');

**Comment by robbrandt** [comment] 2016-08-20 17:54
Like I said, this is just a documentation issue unless you want to put in code that will prevent a fatal error in the event someone doesn't remove them before upgrading.

**Comment by craigh** [comment] 2016-08-20 19:45
> it didn't occur to me to remove the old Profile and Legal modules before copying them back into the new installation along with all my other modules

so you copied the OLD profile/legal over the new ones and then ran the upgrade. right?

**Comment by robbrandt** [comment] 2016-08-20 20:49
Nosir.  In 1.3.10, the modules were located at /modules/Profile and /modules/Legal.  In 1.4.3, they are located at /modules/zikula/legal-module and /modules/zikula/profile-module.  So copying the old modules in with the rest of my old modules means that there were two modules of the same name on the file system, for both Profiles and Legal.

All that needs to happen is for the documentation to change from:
  - copy from your backup ``/userdata``, ``/modules`` and your theme to your new upload. The folders of your modules and themes should be at the exact same place like your backup.

to 

  - copy from your backup ``/userdata``, ``/modules`` and your theme to your new upload. The folders of your modules and themes should be at the exact same place like your backup.  Do NOT include the old Profile and Legal module when copying them into your new installation, as new versions of these are provided.

**Comment by craigh** [comment] 2016-08-20 20:50
GOT IT!

**Comment by robbrandt** [comment] 2016-08-20 20:51
👍

**Comment by craigh** [comment] 2016-08-20 21:20
closed by https://github.com/zikula/core/commit/401c6edf4af54b8f797f61994c6f52b92c4ef491

**Closed by craigh** 2016-08-20 21:20 UTC
Labels: Bug, Core Install & Upgrade, Feedback required, ZCS

**Comment by robbrandt** [comment] 2016-08-22 22:04
👍
