### ISSUE TITLE
Errors When Upgrading Module - Undefined index

### ISSUE THREAD

**Issue by shefik** [zikula/core#2936] opened 2016-07-17 23:33 UTC
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.2
| PHP Version       | 5.6

### Expected behavior

The Exertions module should correctly indicate that a module is available to be upgraded.

### Actual behavior

Error message is thrown:

```Notice: Undefined index: ZikulaExampleModule in /system/ExtensionsModule/Twig/Extension/ExtensionsExtension.php on line 134
Call Stack
#	Time	Memory	Function	Location
1	0.0017	245632	{main}( )	../index.php:0
2	0.8569	36173944	Symfony\Component\HttpKernel\Kernel->handle( )	../index.php:25
3	0.8596	36398128	Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle( )	../Kernel.php:185
4	0.8597	36399368	Symfony\Component\HttpKernel\HttpKernel->handle( )	../ContainerAwareHttpKernel.php:69
5	0.8598	36400320	Symfony\Component\HttpKernel\HttpKernel->handleRaw( )	../HttpKernel.php:62
6	5.5424	63074032	Zikula_EventManager->dispatch( )	../HttpKernel.php:144
7	5.5424	63074080	Symfony\Component\EventDispatcher\EventDispatcher->dispatch( )	../EventManager.php:99
8	5.5425	63076184	Symfony\Component\EventDispatcher\EventDispatcher->doDispatch( )	../EventDispatcher.php:46
9	5.5425	63076536	call_user_func:{/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:181} ( )	../EventDispatcher.php:181
10	5.5425	63076840	Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener->onKernelView( )	../EventDispatcher.php:181
11	5.5796	66175248	Symfony\Bundle\TwigBundle\TwigEngine->renderResponse( )	../TemplateListener.php:117
12	5.5828	66486744	Symfony\Bundle\TwigBundle\TwigEngine->render( )	../TwigEngine.php:97
13	5.5828	66486792	Symfony\Bridge\Twig\TwigEngine->render( )	../TwigEngine.php:72
14	5.5886	66788712	Twig_Template->render( )	../TwigEngine.php:50
15	5.5886	66805424	Twig_Template->display( )	../Template.php:366
16	5.5896	66826312	Twig_Template->displayWithErrorHandling( )	../Template.php:355
17	5.5896	66828152	__TwigTemplate_11fff2efecc80237a58a52d2343324357683caed00f637c5b171a0fddc25d1b1->doDisplay( )	../Template.php:381
18	5.9175	72380416	Zikula\ExtensionsModule\Twig\Extension\ExtensionsExtension->stateLabel( )```

### Steps to reproduce

Install a custom module, and attempt to upgrade it by increasing the version number. Visit the Extension module, and the error will be displayed.

**Comment by craigh** [comment] 2016-07-17 23:44
please zip and attach your custom module.

please specify the zikula version you are using. this is why there is a template - the sub number matters.

**Comment by shefik** [comment] 2016-07-18 00:47
It's Zikula 1.4.2.

**Comment by craigh** [comment] 2016-07-18 12:35
> please zip and attach your custom module.

**Comment by shefik** [comment] 2016-08-12 00:49
I can't attach my custom module. However, I have narrowed down the issue.

File: `/system/ExtensionsModule/Controller/ModuleController.php`
Line: 73

Has this conditional statement:

```if (!$vetoEvent->isPropagationStopped() && $pos == 1) {```

If that statement was removed, the code works without errors.

So, is that conditional statement really needed? If it remains as-is right now, it breaks upgrades.

**Comment by Guite** [comment] 2016-08-13 08:04
@shefik you should check whether you have any event handlers for the `extensions_module.extension_events.regenerate_veto` event. Otherwise the condition should always evaluate to `true`.

**Comment by shefik** [comment] 2016-08-13 08:08
I am not using any event handlers for `extensions_module.extension_events.regenerate_veto`.

**Comment by craigh** [comment] 2016-08-16 00:41
> So, is that conditional statement really needed? If it remains as-is right now, it breaks upgrades.

this is an inflammatory statement and frankly dumb. Of course it is needed. We don't add code to the core just to inconvenience you. It doesn't break **ALL** upgrades. It breaks YOUR upgrade.

> The Extensions module should correctly indicate that a module is available to be upgraded.

it does this. I just tested with with both Legacy and Core-2.0 type modules. It works. The modules display and upgrade correctly.

You've been asked to provide your module and you won't or can't.

fine.

I cannot reproduce the issue with YOUR module without it. So closing as not core.

**Closed by craigh** 2016-08-16 00:41 UTC
Labels: Feedback required
