### ISSUE TITLE
Warning: ini_set(): A session is active. You cannot change the session module's ini settings at this time

### ISSUE THREAD

**Issue by shefik** [zikula/core#3898] opened 2018-04-14 10:49 UTC
| Q                 | A
| ----------------- | ---
| Zikula Version    | 2.0.7
| PHP Version       | 7.2.1

### Expected behavior

Error message should not display.

### Actual behavior

Error:

`Warning: ini_set(): A session is active. You cannot change the session module's ini settings at this time (500 Internal Server Error)`

### Steps to reproduce

Try to login. The message appears immediately after the form is submitted.

**Comment by shefik** [comment] 2018-06-02 03:29
Issue persists with Zikula 2.0.7.

**Comment by Guite** [comment] 2018-06-20 16:42
I've just looked into what happens here.

First, the problem is caused by that `ini_set()` is used to manipulate a session related PHP option after a session already has been started.

The concrete place where `ini_set()` is being executed is in `Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage#regenerate($destroy = false, $lifetime = null)` which calls: `ini_set('session.cookie_lifetime', $lifetime);`

Basically when a login is executed our access controller calls an access helper at https://github.com/zikula/core/blob/2.0/src/system/UsersModule/Controller/AccessController.php#L129 which then calls the session `migrate` method in https://github.com/zikula/core/blob/2.0/src/system/UsersModule/Helper/AccessHelper.php#L112 - this `migrate` call calls the `NativeSessionStorage#regenerate()` method shown above.

So, we have two options to get rid of this problem:

1. Easy but dirty
We could simply replace
```
$this->session->migrate(true, $lifetime);
```
by
```
$reportingLevel = error_reporting(E_ALL & ~E_WARNING);
$this->session->migrate(true, $lifetime);
error_reporting($reportingLevel);
```
to suppress the warning.

2. Clean but not that easy
For a better solution we would need to avoid starting the session at all before the migrate call is done.
Of course we could easily move https://github.com/zikula/core/blob/2.0/src/system/UsersModule/Controller/AccessController.php#L128 one line further below. But how to handle things like https://github.com/zikula/core/blob/2.0/src/system/UsersModule/Controller/AccessController.php#L48 where the session is accessed already much earlier in the controller code?

@craigh

**Comment by craigh** [comment] 2018-06-21 00:54
this happens on a clean install with no additional modules, etc?

**Comment by shefik** [comment] 2018-06-21 00:56
I’ve only tried it on upgrade, and it happens there.

**Comment by Guite** [comment] 2018-06-21 07:20
> this happens on a clean install with no additional modules, etc?

Yes.

**Comment by craigh** [comment] 2018-06-21 10:51
don't remember this happening in earlier releases. What changed?

**Comment by Guite** [comment] 2018-06-21 10:54
> What changed?

This happens only in PHP 7.2.

**Comment by Guite** [comment] 2018-07-05 09:47
I added PHP 7.2 to Travis builds and this fails for 2.0 and master. Interestingly the build succeeds for the 1.5 branch.

Raising severity to blocker.

**Comment by craigh** [comment] 2018-07-05 14:23
Admittedly I do. It understand the problem. But it seems like this would also be a problem for symfony and therefor something they would have solved?

**Comment by Guite** [comment] 2018-07-06 06:31
I decided to suppress this warning centrally in our session storage subclass. Not the cleanest solution, but first it does not have any side-effects and second it also works if any other session access is done from the outside (e.g. by an event subscriber or a listener of a module).

**Comment by Guite** [comment] 2018-07-06 06:33
While everything works now on my test sites, the problem still appears in Travis. Reopening...

**Comment by Guite** [comment] 2018-07-06 07:48
Fixed by #3914

**Closed by Guite** 2018-07-06 07:48 UTC
Labels: Blocker, Bug

**Comment by bunialex** [comment] 2020-04-12 01:40
You may try using PHP 7.1, the session handling is different and it worked for me.

**Comment by Guite** [comment] 2020-04-12 06:25
@bunialex the final fix is here: https://github.com/symfony/symfony/pull/35656/files
