### ISSUE TITLE
Return url not decoded back after encoding

### ISSUE THREAD

**Issue by Kaik** [zikula/core#3744] opened 2017-08-03 21:42 UTC
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.6
| PHP Version       | 7.x

### Expected behavior
Login and go to page that requested user access via return url.

### Actual behavior
return url looks like this `` http://core14.desktop.local/%2Fusers%2Fadmin%2Fuser%2Fmodify%2F2 ``

### Steps to reproduce
Login as admin then go to any admin page like modules list wait until the session expires or log out on another tab then refresh and log in.

I wonder is it my setup or it is a bug, later on, will check if it is present in 15 and 20

**Comment by Guite** [comment] 2017-08-03 21:46
> will check if it is present in 15 and 20

Yes please.

**Comment by Kaik** [comment] 2017-08-07 16:29
I will check it please allow me some time to do that as I'm now completely in different place. I will do that within 2 weeks. I think i is my setup but need to check what happens because it might be some edge case bug.

**Comment by craigh** [comment] 2017-08-25 20:06
status?

**Comment by Guite** [comment] 2017-08-28 15:26
I can not reproduce this.
After logging out and reloading an admin page I am redirected to for example `login?returnUrl=%252Fblocks%252Fadmin%252Fview`. After logging in again I properly end at `/blocks/admin/view`.

**Comment by Guite** [comment] 2017-08-28 15:28
I also tested the user modification page (since @Kaik used this above). After logging out the login page url is `/login?returnUrl=%252Fusers%252Fadmin%252Fuser%252Fmodify%252F3` and after logging in again I am redirected to `/users/admin/user/modify/3` without problems.

**Comment by Guite** [comment] 2017-08-28 15:30
So either it was an issue in 1.4.x only (fixed in 1.5+) (I doubt that) or it is somehow related to @Kaik's setup.

**Closed** 2017-08-28 15:35 UTC
Labels: Bug, Feedback required
