### ISSUE TITLE
Hooks can not be attached with ci build 80

### ISSUE THREAD

**Issue by rallek** [zikula/core#2626] opened 2015-10-08 19:26 UTC
in 1.4.0 I hooked ezcomments on the news module by dropping the hook provider into the ui_hooks area of news.

In 1.4.1 ci build 80 I can not grap the hook provider anymore. I tried in Andreas08 and Bootstrap theme.

**Comment by craigh** [comment] 2015-10-13 09:17
my guess here is that in my refactoring of loading of page assets, something got left out somehow.

**Comment by craigh** [comment] 2015-10-13 23:12
also there is an undefined stylesheet

`<link rel="stylesheet" href="/core.git/src/" type="text/css">`

**Comment by craigh** [comment] 2015-11-07 14:56
I have just tested this. I am using a 'composed' version and not a build.

I am able to
- [x] install News 3.1.1 (cloned)
- [x] use and interact with News as would normally be expected.
- [x] install EZComments 3.0.1 (cloned)
- [x] use and interact with EZ comments as would normally be expected
- [x] hook EZComments to News using the Hook UI
- [x] make a comment on hooked news article as expected

therefore, I cannot reproduce the behavior.

things I cannot check at the moment that I have noticed as a difference in your installations and mine:
- [ ] installation at root directory (e.g. `localhost` vs `localhost/sub/dir/`)
- [ ] installation on windows

**Comment by rallek** [comment] 2015-11-08 12:54
I made a new install on my shared hosting (webgo, not allinkl). I installed ci build 104 via wget and web installer. added the master version of news and EZComments. Installation went fine. 

Opening thze News admin going to the hook settings I can see the hook of EZComments. But I can not drag and drop it.

**Comment by craigh** [comment] 2015-11-08 15:44
fixed by https://github.com/zikula/core/commit/d8fb5412498f98c14bb0e2f18f6f5c6d0e8d50b2

**Closed** 2015-11-08 15:47 UTC
Labels: Bug, Javascript
