### ISSUE TITLE
If install have an error there should not be finishing possible

### ISSUE THREAD

**Issue by rallek** [zikula/core#3419] opened 2017-01-28 18:46 UTC
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.6dev (74)
| PHP Version       | 5.5

### Expected behavior
Installation should show something when failing the installation

### Actual behavior
I installed 1.4.6 ci build 74 with my german translation. During installation there was the message that something went wrong during installation of the permissions module. Might be there is something wrong inside my translation (still a lot of translations are marked as unclear). But never the less, if something is broken during installation I should not be able to press ``finish`` and get an error. There should be another page with an explanation what was going wrong and some hints what to do or what was going wrong.

**Comment by rallek** [comment] 2017-01-28 18:50
for information: Installation without my translation was working fine. So this ticket is not for installtion problems of permission module

**Comment by Guite** [comment] 2017-06-20 18:47
refs #2540

**Comment by Guite** [comment] 2020-01-31 18:30
Closing this issue, because we now use more reasonable defaults.
Of course there is still the possibility that problems occur, in these cases we need to investigate the causes.
For the end user it won't make (more) sense to stop the whole process. So I think the current state is better; some potential error alerts might be non-critical and things still work nevertheless.

**Closed by Guite** 2020-01-31 18:30 UTC
Labels: Core Install/Upgrade, Feature
