### ISSUE TITLE
Fatal error: Call to a member function rowCount()

### ISSUE THREAD

**Issue by shefik** [zikula/core#2284] opened 2015-02-23 04:26 UTC
If you submit the Installer form without filling out the form, it throws the following error:

"Fatal error: Call to a member function rowCount() on boolean in /lib/Zikula/Bundle/CoreInstallerBundle/Validator/CoreInstallerValidator.php on line 35"

Zikula 1.4.0 build 452

**Comment by shefik** [comment] 2015-02-23 05:04
The error occurs when you select "MySQL", but not when you select "PostgreSQL".

**Comment by craigh** [comment] 2015-02-23 11:16
> the Installer form

which? there are 4

**Comment by cmfcmf** [comment] 2015-02-23 11:47
@craigh See the error message: `CoreInstallerValidator.php line 35`.

**Comment by craigh** [comment] 2015-02-23 12:20
@shefik what is the state of the database when you receive this error? Did it have tables?

**Comment by craigh** [comment] 2015-02-23 12:37
http://stackoverflow.com/questions/1451720/equivalent-of-mysql-list-tables-in-php-pdo

this discussion seems to indicate that doing cross-platform database connection validation is quite difficult until we can use Doctrine which isn't available at this point.

**Comment by shefik** [comment] 2015-02-26 03:27
@craigh Yes, the database was completely empty. Try submitting the form, without entering any values, and the error will occur. Perhaps more form validation can help?

**Comment by craigh** [comment] 2015-02-26 20:54
> Perhaps more form validation can help?

the problem is that the validations are occurring in the wrong order apparently. There is already validation for NonNull values

**Comment by Guite** [comment] 2015-03-04 17:00
@shefik can you please retest with #2310 ?

**Comment by Guite** [comment] 2015-03-06 06:55
Fixed by #2310. @shefik please reopen in case you still experience problems.

**Closed by Guite** 2015-03-06 06:55 UTC
Labels: Install & Upgrade
