### ISSUE TITLE
Update POT file for installer

### ISSUE THREAD

**Issue by shefik** [zikula/core#2233] opened 2015-02-08 11:11 UTC
The strings contained in the installer template are not found in the zikula.pot file. For example, this is not found:

"Useful resources"

**Comment by Guite** [comment] 2015-02-08 11:13
Probably a duplicate of #2191...  @craigh  ?

**Closed** 2015-02-08 11:31 UTC
Labels: Duplicate

**Comment by craigh** [comment] 2015-02-08 11:33
Sadly, the get text module is not currently capable of extracting the strings from twig templates.
