### ISSUE TITLE
Zikula 1.3 themes in zikula 1.4 theme variables error

### ISSUE THREAD

**Issue by Kaik** [zikula/core#2556] opened 2015-08-05 15:37 UTC
I have tested few themes from zikula/themes and this is error which occurs 
![screenshot from 2015-08-05 17 24 31](https://cloud.githubusercontent.com/assets/966910/9089745/0ca90072-3b97-11e5-8a79-02738e584378.png)

I have checked and its due to this line https://github.com/zikula/core/blob/1.4/src/system/ThemeModule/Api/UserApi.php#L57
not working with this one
https://github.com/zikula/core/blob/1.4/src/lib/legacy/Zikula/View/Theme.php#L681

**Comment by KratorD** [comment] 2015-08-18 06:07
Hello, this error was fixed in the issue 2523:
https://github.com/zikula/core/issues/2523

Thanks.

**Comment by Kaik** [comment] 2015-08-18 20:17
Hi, I think I was at that time, any way line's I have mentioned are still looking like it would no work as the $args array here https://github.com/zikula/core/blob/1.4/src/system/Zikula/Module/ThemeModule/Api/UserApi.php#L57 contains variables key and only that key is returned, while here https://github.com/zikula/core/blob/1.4/src/lib/legacy/Zikula/View/Theme.php#L681
You are checking only if returned value is an array not if it contains variable key which is not because previous line is already returning data under variable key without key itself.

So it is not fixed.

**Comment by craigh** [comment] 2015-09-02 19:52
@Kaik I'm am quite sure this is fixed. I am closing it as a duplicate of #2523. The screenshot you posted is from before #2523 was applied. If you can reproduce the error, please reopen the ticket. thanks.

**Closed by craigh** 2015-09-02 19:52 UTC
