### ISSUE TITLE
Translation functionality - current status + test enviroment.

### ISSUE THREAD

**Issue by Kaik** [zikula/core#2477] opened 2015-05-28 13:21 UTC
Hi, for some time I'm doing translation part for Zikula and I need you to do some tests. Mainly current status you can also test my pull request this way.
For tests Zikula 1.4 installed with additional languages.
I'm using this two languages at the moment to test how and if legacy is working

```
https://github.com/zikula-communities/polish/tree/master/src/app/Resources/locale
https://github.com/zikula-communities/german/tree/master/locale
```
To install languages please:
* download pl and de folder into ``` app/Resources/locale ```
* turn on multilingual settings in site admin - general settings - localisation settings.
* reload multilingual routes

This should activate all languages so you can change site language changing language url part /en/ to /pl/ or /de/
First thing to test is url's some for me have current language others fall to default one which is wrong.
If you find odd things please let me know.

Yesterday @craigh merged simple translation testing enviroment to breakit module here is screenshoot how it look.
![screencapture-core-dev-en-breakit-translations-1432981739936](https://cloud.githubusercontent.com/assets/966910/7896872/4a17ebfc-06c8-11e5-963c-7cea1e001ee7.png)

**Comment by craigh** [comment] 2015-05-30 16:40
I've done what you've asked. Not sure what I'm supposed to do next...

![screen shot 2015-05-30 at 12 39 38 pm](https://cloud.githubusercontent.com/assets/350048/7898273/f7be8ffe-06c8-11e5-85d9-1753a3053b99.png)

**Comment by craigh** [comment] 2015-05-30 23:04
this is **with** the PR branch.

![screen shot 2015-05-30 at 7 03 32 pm](https://cloud.githubusercontent.com/assets/350048/7899758/98922046-06fe-11e5-87c0-d06c755dfe2d.png)

**Comment by Kaik** [comment] 2015-06-02 16:02
Hi @craigh this is awesome I can't wait to test it I will check all changes you made soon. You probably solved issues I have found recently working with translations in block (new block abstract) but that was with old version of my PR so can't wait to test all this stuff. Will be back soon

**Comment by Guite** [comment] 2015-06-06 03:50
What's the status here?

**Comment by craigh** [comment] 2015-06-07 10:49
closing this as it seems redundant/duplicate of #2460

**Closed by craigh** 2015-06-07 10:49 UTC
Labels: Language/Translation
