### ISSUE TITLE
Option to increase/decrease timeouts for admins and other groups

### ISSUE THREAD

**Issue by marcpare4** [zikula/core#261] opened 2012-02-06 20:13 UTC
Feature request for 1.3.x:

 I was wondering if it would be possible to add the feature of increasing/decreasing the timeouts for admins and the rest of the groups. As admin, I find that I timeout often and, on one of my site, I thought it would be great if I could increase the timeouts for admins and not the other groups.

Actually, it would be even better if there could be a way to establish timeouts for all groups with some kind of drop down menu where you could pick the groups on the site. 

(timeout is set through the SecurityCentre->Settings module in 1.2.8)

Cheers,

Marc

**Comment by Guite** [comment] 2017-06-20 18:33
I disagree :-1: 
Better would be to repair the cause of the timeouts so they don't happen anymore.

Closing this. Feel free to reopen if you have objections.

**Closed by Guite** 2017-06-20 18:33 UTC
Labels: Feature
