### ISSUE TITLE
Catchable Fatal Error: Argument 1 passed

### ISSUE THREAD

**Issue by luilope1** [zikula/core#2384] opened 2015-03-31 18:10 UTC
Hi,
I'm testing zikula 1.4 and I have this problem:

In profile.tpl
{modfunc modname='ZikulaMembersModule' type='user' func='result'  yo='1'}

```
[1] Symfony\Component\Debug\Exception\ContextErrorException: Catchable Fatal Error: Argument 1 passed to Zikula\MembersModule\Controller\UserController::resultAction() must be an instance of Symfony\Component\HttpFoundation\Request, array given
    at n/a
        in C:\xampp\htdocs\Zikula_Core-1.4.0.rc1\modules\zikula\members-module\Controller\UserController.php line 2076
   2075
   2076 public function resultAction(Request $request)
   2077 {
    
    at Symfony\Component\Debug\ErrorHandler->handleError('4096', 'Argument 1 passed to Zikula\MembersModule\Controller\UserController::resultAction() must be an instance of Symfony\Component\HttpFoundation\Request, array given', 'C:\xampp\htdocs\Zikula_Core-1.4.0.rc1\modules\zikula\members-module\Controller\UserController.php', '2076', array())
        in C:\xampp\htdocs\Zikula_Core-1.4.0.rc1\modules\zikula\members-module\Controller\UserController.php line 2076

    at Zikula\MembersModule\Controller\UserController->resultAction(array('yo' => '1'))
        in  line 

    at call_user_func(array(object(UserController), 'resultAction'), array('yo' => '1'))
        in C:\xampp\htdocs\Zikula_Core-1.4.0.rc1\lib\util\ModUtil.php line 1155

    at ModUtil::exec('ZikulaMembersModule', 'user', 'result', array('yo' => '1'), false, null)
        in C:\xampp\htdocs\Zikula_Core-1.4.0.rc1\lib\util\ModUtil.php line 1205

    at ModUtil::func('ZikulaMembersModule', 'user', 'result', array('yo' => '1'))
        in C:\xampp\htdocs\Zikula_Core-1.4.0.rc1\lib\legacy\viewplugins\function.modfunc.php line 67

    at smarty_function_modfunc(array('modname' => 'ZikulaMembersModule', 'type' => 'user', 'func' => 'result', 'yo' => '1'), object(Zikula_View))
        in C:\xampp\htdocs\Zikula_Core-1.4.0.rc1\app\cache\prod\ztemp\view_compiled\Zikula\members-module\user\profile--t_Zikula\Theme\BootstrapTheme-l_en.php line 33

    at include('C:\xampp\htdocs\Zikula_Core-1.4.0.rc1\app\cache\prod\ztemp\view_compiled\Zikula\members-module\user\profile--t_Zikula\Theme\BootstrapTheme-l_en.php')
        in C:\xampp\htdocs\Zikula_Core-1.4.0.rc1\lib\legacy\Zikula\View.php line 2960

    at Zikula_View->_fetch('user/profile.tpl', '', '', false)
        in C:\xampp\htdocs\Zikula_Core-1.4.0.rc1\lib\legacy\Zikula\View.php line 763

    at Zikula_View->fetch('user/profile.tpl')
        in C:\xampp\htdocs\Zikula_Core-1.4.0.rc1\modules\zikula\members-module\Controller\UserController.php line 204

    at Zikula\MembersModule\Controller\UserController->profileAction(object(Zikula_Request_Http))
        in  line 

    at call_user_func_array(array(object(UserController), 'profileAction'), array(object(Zikula_Request_Http)))
        in C:\xampp\htdocs\Zikula_Core-1.4.0.rc1\lib\util\ModUtil.php line 1153

    at ModUtil::exec('ZikulaMembersModule', 'user', 'profile', array(), false, null)
        in C:\xampp\htdocs\Zikula_Core-1.4.0.rc1\lib\util\ModUtil.php line 1205

    at ModUtil::func('ZikulaMembersModule', 'user', 'profile')
        in C:\xampp\htdocs\Zikula_Core-1.4.0.rc1\lib\Zikula\Bundle\CoreBundle\EventListener\LegacyRouteListener.php line 96

    at Zikula\Bundle\CoreBundle\EventListener\LegacyRouteListener->onKernelRequest(object(GetResponseEvent), 'kernel.request', object(TraceableEventDispatcher))
        in  line 

    at call_user_func(array(object(LegacyRouteListener), 'onKernelRequest'), object(GetResponseEvent), 'kernel.request', object(TraceableEventDispatcher))
        in C:\xampp\htdocs\Zikula_Core-1.4.0.rc1\vendor\symfony\symfony\src\Symfony\Component\EventDispatcher\Debug\WrappedListener.php line 61

    at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(object(GetResponseEvent), 'kernel.request', object(Zikula_EventManager))
        in  line 

    at call_user_func(object(WrappedListener), object(GetResponseEvent), 'kernel.request', object(Zikula_EventManager))
        in C:\xampp\htdocs\Zikula_Core-1.4.0.rc1\vendor\symfony\symfony\src\Symfony\Component\EventDispatcher\EventDispatcher.php line 164

    at Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(array(object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'kernel.request', object(GetResponseEvent))
        in C:\xampp\htdocs\Zikula_Core-1.4.0.rc1\vendor\symfony\symfony\src\Symfony\Component\EventDispatcher\EventDispatcher.php line 53

    at Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', object(GetResponseEvent))
        in C:\xampp\htdocs\Zikula_Core-1.4.0.rc1\vendor\symfony\symfony\src\Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher.php line 167

    at Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.request', object(GetResponseEvent), null)
        in C:\xampp\htdocs\Zikula_Core-1.4.0.rc1\lib\legacy\Zikula\EventManager.php line 99

    at Zikula_EventManager->dispatch('kernel.request', object(GetResponseEvent))
        in C:\xampp\htdocs\Zikula_Core-1.4.0.rc1\vendor\symfony\symfony\src\Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher.php line 112

    at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch('kernel.request', object(GetResponseEvent))
        in C:\xampp\htdocs\Zikula_Core-1.4.0.rc1\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\HttpKernel.php line 126

    at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Zikula_Request_Http), '1')
        in C:\xampp\htdocs\Zikula_Core-1.4.0.rc1\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\HttpKernel.php line 66

    at Symfony\Component\HttpKernel\HttpKernel->handle(object(Zikula_Request_Http), '1', true)
        in C:\xampp\htdocs\Zikula_Core-1.4.0.rc1\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel.php line 64

    at Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(object(Zikula_Request_Http), '1', true)
        in C:\xampp\htdocs\Zikula_Core-1.4.0.rc1\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Kernel.php line 186

    at Symfony\Component\HttpKernel\Kernel->handle(object(Zikula_Request_Http))
        in C:\xampp\htdocs\Zikula_Core-1.4.0.rc1\index.php line 25
```

**Comment by craigh** [comment] 2015-03-31 18:13
what is `ZikulaMembersModule` ?

**Comment by craigh** [comment] 2015-03-31 18:13
are you testing RC2? (build 515)

**Comment by craigh** [comment] 2015-03-31 18:15
> in C:\xampp\htdocs\Zikula_Core-1.4.0.rc1

please upgrade to RC2 and test again.

**Comment by luilope1** [comment] 2015-03-31 18:24
zikulaMemberModule is a own module that I'm converting zikula 1.4.
Tomorrow I will continue testing zikula RC2.

Sorry for my English.

**Comment by craigh** [comment] 2015-03-31 18:26
upload to your github acct and maybe I can take a look, but I would assume that the problem is with the module, not the core :smile: 

I'm not sure the old `{modfunc}` plugin is going to be useful here. but I'm not sure. you may have to pass the `Request` object to it.

closing as not core.

**Closed by craigh** 2015-03-31 18:26 UTC
Labels: unconfirmed

**Comment by shefik** [comment] 2015-03-31 20:50
@luilope1 Instead of ```{modfunc}``` try:

```
{route name='zikulamembersmodule_user_display'  yo=1}
```

Also, make sure you have routes set-up in your module.

**Comment by Kaik** [comment] 2015-04-01 09:03
I just had similar error. I tried to access directly abouts action here
```
namespace Kaikmedia\PagesModule\Controller;

use DataUtil;
use ModUtil;
use SecurityUtil;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use System;
use UserUtil;
use ServiceUtil;
use Zikula\Core\Controller\AbstractController;
use Zikula\Core\Event\GenericEvent;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route; // used in annotations - do not remove
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method; // used in annotations - do not remove
use Symfony\Component\Routing\RouterInterface;
use Kaikmedia\PagesModule\Entity\PagesEntity as Page; 


/**
  * @Route("") <- this line generates error 
 * Class UserController
 * @package Kaikmedia\PagesModule\Controller
 */
class UserController extends AbstractController
{
    /**
     * @Route("")
     *
     * The default entry point.
     *
     * This redirects back to the default entry point for the Users module.
     *
     * @return RedirectResponse
     */
    public function indexAction()
    {
        return new RedirectResponse($this->get('router')->generate('kaikmediapagesmodule_user_abouts', array(), RouterInterface::ABSOLUTE_URL));
    }
    
    /**
     * @Route("/abouts")
     * 
     * Display item.
     *
     * Parameters passed via GET:
     * --------------------------------------------------
     * numeric uid   The user account id (uid) of the user for whom to display profile information; optional, ignored if uname is supplied, if not provided
     *                  and if uname is not supplied then defaults to the current user.
     * string  uname The user name of the user for whom to display profile information; optional, if not supplied, then uid is used to determine the user.
     * string  page  The name of the Profile "page" (view template) to display; optional, if not provided then the standard view template is used.
     *
     * @return RedirectResponse|string The rendered template output.
     *
     * @throws AccessDeniedException on failed permission check
     */
    public function aboutsAction(Request $request)
    {
        // Security check
        if (!SecurityUtil::checkPermission($this->name.'::view', '::', ACCESS_READ)) {
            throw new AccessDeniedException();
        }
        

        
        
        $request->attributes->set('_legacy', true); // forces template to render inside old theme
        return $this->render('KaikmediaPagesModule:User:list.html.twig',
                array('ZUserLoggedIn' => \UserUtil::isLoggedIn(),
                    ));
    }    
}
```
This was reason for passed array instead of request object error. Maybe it will help :)

**Comment by luilope1** [comment] 2015-04-01 16:33
I tried with
```
 {route  name='zikulamembersmodule_user_result' yo='1'}
```
and the output is:
```
/Zikula_Core-1.4.0.rc1/members/result?yo=1
```
but I need the result of this url

I tried with:
```
 {modfunc modname='ZikulaIntercomModule' type='user' func='inbox' sortby='subject' sortorder='ASC'}
```
And the same error:
Catchable Fatal Error: Argument 1 passed to Zikula\IntercomModule\Controller\UserController::inboxAction() must be an instance of Symfony\Component\HttpFoundation\Request, array given

**Comment by Guite** [comment] 2015-04-01 18:02
Maybe this helps: https://translate.google.com/translate?sl=de&tl=en&js=y&prev=_t&hl=de&ie=UTF-8&u=http%3A%2F%2Fget-the-most.de%2Fblog%2Fdisplay%2F2014%2F3%2F20%2Fcontroller-funktionen-in-templates-einbinden%2F&edit-text=&act=url

**Comment by luilope1** [comment] 2015-04-02 17:59
Thank you very much. This code works correctly
```
 {php} 
  $request = \ServiceUtil::get('request');
  $request->query->set('yo', '1'); 
 {/php} 
 {modfunc modname='ZikulaMembersModule' type='user' func='result'}
```

**Comment by craigh** [comment] 2015-04-02 18:11
since that seems kind of "hacky" you might consider a different method (if you are refactoring for 1.4 anyway). Maybe an API method or directly injectin the result into the template in the controller.

**Comment by luilope1** [comment] 2015-04-03 08:23
I could give an example of how to use another method api or directly injectin the result into the template in the controller.

**Comment by craigh** [comment] 2015-04-03 11:49
> I could give an example of how to use another method api or directly injectin the result into the template in the controller.

I assume you are *requesting* and example? (give = provide)

API: create a new API method that does what you are asking. call that using `{modfuncapi}` instead. call same from the controller you are referencing if it is used elsewhere.

template injection: do the same as you are doing above, but add your new data:
```twig
        $request->attributes->set('_legacy', true); // forces template to render inside old theme
        return $this->render('KaikmediaPagesModule:User:list.html.twig',
                array('ZUserLoggedIn' => \UserUtil::isLoggedIn(),
                          'myNewData' => getMyNewData(),
                    ));
```

then display the result in your template
`{{ myNewData }}`

**Comment by luilope1** [comment] 2015-04-04 17:20
Thank you very much. I will work in this example.
Sorry for my English.
