### ISSUE TITLE
Update 1.4.1 -> 1.4.2 fails with ZIKULACORE_CURRENT_INSTALLED_VERSION error

### ISSUE THREAD

**Issue by MrMontesa** [zikula/core#2845] opened 2016-04-12 11:31 UTC
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.2
| PHP Version       | 5.6.17

### Actual behavior
I've tried to update one of my sites from 1.4.1 to 1.4.2. This is what I've done on console after downloading the new relase (c&p from history)

```
cd ~/htdocs/
mv -r sebsys sebsys.20160412
tar -xvf Zikula_Core-1.4.2.build166.tar
mv Zikula_Core-1.4.2 sebsys
cd sebsys
cp config/config.php config/personal_config.php
vi config/personal_config.php    <- adding my local stuff
chmod 400 config/personal_config.php
cp app/config/parameters.yml app/config/custom_parameters.yml
vi app/config/custom_parameters.yml     <- adding my local stuff
chmod 400 app/config/custom_parameters.yml
chmod -R 777 app/cache lpp/ogs
php app/console zikula:upgrade
```

After executing the console it spits the following error message:

```
The current installed version of Zikula is reporting (ZIKULACORE_CURRENT_INSTALLED_VERSION). You must upgrade to version (1.3.6) before you can use this upgrade.
```

When trying to use web GUI to upgrade I get redirected to the installer.
Then cross-checked the installed = 1 in config.php which was set to 0.
When setting it to 1 the webserver returns error 500

```
Oops! An Error Occurred

The server returned a "500 Internal Server Error".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

Unable to find template "ZikulaCoreInstallerBundle::error.html.twig" (looked into: /web/1/000/027/915/75642/htdocs/sebsys/vendor/symfony/symfony/src/Symfony/Bridge/Twig/Resources/views/Form).
```

I'm a bit puzzled how to continue troubleshooting.
Thanks for your help.

**Comment by MrMontesa** [comment] 2016-04-12 13:16
From the CLI error message it seems that the "installed version" cannot be pulled out of the configuraion.
How's this info extracted? Can I do some SQL/config queries to exclude something is wrong with my 1.4.1 install?
Thanks

**Comment by craigh** [comment] 2016-08-09 13:02
I cannot confirm this. I was able to upgrade 1.4.1 -> 1.4.2 via the console with no problem. I suspect you are doing something incorrectly because of this comment:

> Then cross-checked the installed = 1 in config.php which was set to 0.

the `config.php` file no longer functions as the primary config file and only remains for BC issues with DBUtil. You should be setting `installed: true` in the `app/config/custom_parameters.yml` file instead.

I suspect you did not follow the instructions in the `docs/en/UPGRADE-1.4.md` document as carefully as you initially thought. While I agree these docs are not as perfectly clear as I would like, there are also some "legacy" issues in _your thought process_ that probably have effected your work.

**Comment by craigh** [comment] 2016-08-09 13:03
closing as unconfirmed. please re-open if you can replicate the behavior.

**Closed by craigh** 2016-08-09 13:03 UTC
Labels: Bug, Core Install & Upgrade, unconfirmed
