### ISSUE TITLE
the left admin menu is not working

### ISSUE THREAD

**Issue by rallek** [zikula/core#3695] opened 2017-07-24 17:38 UTC
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.5.0 ci 231
| PHP Version       | 5.6

### Expected behavior
it should work like under 1.4.6

### Actual behavior
before upgrade I was able to see the left admin menu after clicking on the icon in the menu bar. Now there is a white space

### Steps to reproduce
upgrade from 1.4.6 to 1.5.0
change the theme to bootstrap theme
Try to open the mmenue

before:
![grafik](https://user-images.githubusercontent.com/935250/28536299-78a6adfa-70a7-11e7-83dd-ade0029528c8.png)
after:
![grafik](https://user-images.githubusercontent.com/935250/28536330-926f098a-70a7-11e7-918e-b839762786d6.png)

**Comment by rallek** [comment] 2017-07-25 06:51
not shure if it is really a bug. Today at another PC the menu is showing up as usual.

**Comment by Guite** [comment] 2017-07-25 11:43
Can not reproduce: works fine here in both 1.5 and 2.0.

**Comment by craigh** [comment] 2017-07-25 12:13
I cannot reproduce either. Closing since you aren't sure. please reopen if you continue to have the problem.

**Closed by craigh** 2017-07-25 12:13 UTC
Labels: Bug, UI/UX
