### ISSUE TITLE
RC1 Test - profile permission issue

### ISSUE THREAD

**Issue by rallek** [zikula/core#2267] opened 2015-02-21 18:46 UTC
I am testing for #2264 

My test environment:
* RC1 from zikula.org
* one normal user
* profile extension installed
* profile module configured in general settings
* bootstrap theme activated

The user is logged in and opening "my Account". The link to profile is visible. But if the user click it he do not have permissions.

If the admin do the same the admin see the administration page for profile (there where you can select/unselect the fields)

do I have to do anything inside permission settings? This was not necessary in older versions.

**Comment by craigh** [comment] 2015-02-21 19:55
is this a duplicate of #2268 ?

**Comment by craigh** [comment] 2015-02-21 20:00
This may be a bug with Profile and not core, but should still block RC1

**Comment by rallek** [comment] 2015-02-21 21:44
It looks like a wrong route:
http://rallek.k62.org/profile/admin/view?uid=3

**Closed** 2015-02-22 19:45 UTC
Labels: Bug
