### ISSUE TITLE
ExtensionVarEntity cannot unserialize SystemPlugin_Imagine_Preset

### ISSUE THREAD

**Issue by craigh** [zikula/core#2966] opened 2016-08-14 22:12 UTC
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.3
| PHP Version       | 5.6

### Expected behavior
`php app/console debug:event-dispatcher` works without error. ExtensionVarApi

### Actual behavior
    [Craigs-iMac2013:htdocs/core.git/src] craig% php app/console debug:event-dispatcher -vvv

    Registered Listeners Grouped by Event
    =====================================

                                                             
      [Symfony\Component\Debug\Exception\ContextErrorException]  
      Warning: Class __PHP_Incomplete_Class has no unserializer  
                                                             

    Exception trace:
     () at /Applications/MAMP/htdocs/core.git/src/system/ExtensionsModule/Entity/ExtensionVarEntity.php:85
     Symfony\Component\Debug\ErrorHandler->handleError() at n/a:n/a
     unserialize() at /Applications/MAMP/htdocs/core.git/src/system/ExtensionsModule/Entity/ExtensionVarEntity.php:85
     Zikula\ExtensionsModule\Entity\ExtensionVarEntity->getValue() at /Applications/MAMP/htdocs/core.git/src/system/ExtensionsModule/Api/VariableApi.php:83
     Zikula\ExtensionsModule\Api\VariableApi->initialize() at /Applications/MAMP/htdocs/core.git/src/system/ExtensionsModule/Api/VariableApi.php:157
     Zikula\ExtensionsModule\Api\VariableApi->getAll() at /Applications/MAMP/htdocs/core.git/src/system/MailerModule/Api/MailerApi.php:100
     Zikula\MailerModule\Api\MailerApi->__construct() at /Applications/MAMP/htdocs/core.git/src/app/cache/dev/appDevDebugProjectContainer.php:5630
     appDevDebugProjectContainer->getZikulaMailerModule_Api_MailerService() at /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:314
     Symfony\Component\DependencyInjection\Container->get() at /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:454
     Symfony\Component\DependencyInjection\ContainerBuilder->get() at /Applications/MAMP/htdocs/core.git/src/lib/legacy/Zikula/ServiceManager.php:114
     Zikula_ServiceManager->get() at /Applications/MAMP/htdocs/core.git/src/app/cache/dev/appDevDebugProjectContainer.php:6046
     appDevDebugProjectContainer->getZikulaSecuritycenterModule_FilterListenerService() at /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:314
     Symfony\Component\DependencyInjection\Container->get() at /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:454
     Symfony\Component\DependencyInjection\ContainerBuilder->get() at /Applications/MAMP/htdocs/core.git/src/lib/legacy/Zikula/ServiceManager.php:114
     Zikula_ServiceManager->get() at /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/ContainerAwareEventDispatcher.php:183
     Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher->lazyLoad() at /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/ContainerAwareEventDispatcher.php:125
     Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher->getListeners() at /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php:99
     Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->getListeners() at /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/TextDescriptor.php:373
     Symfony\Bundle\FrameworkBundle\Console\Descriptor\TextDescriptor->describeEventDispatcherListeners() at /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Descriptor/Descriptor.php:73
     Symfony\Bundle\FrameworkBundle\Console\Descriptor\Descriptor->describe() at /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Component/Console/Helper/DescriptorHelper.php:72
     Symfony\Component\Console\Helper\DescriptorHelper->describe() at /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/EventDispatcherDebugCommand.php:80
     Symfony\Bundle\FrameworkBundle\Command\EventDispatcherDebugCommand->execute() at /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:259
     Symfony\Component\Console\Command\Command->run() at /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:863
     Symfony\Component\Console\Application->doRunCommand() at /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:192
     Symfony\Component\Console\Application->doRun() at /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:92
     Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:123
     Symfony\Component\Console\Application->run() at /Applications/MAMP/htdocs/core.git/src/app/console:44

    debug:event-dispatcher [--format FORMAT] [--raw] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command> [<event>]

----

I was able to determine the cause of the problem which is that the modvar `systemplugin.imagine` / `presets` has this as its value:

    string(327) "a:1:{s:7:"default";C:27:"SystemPlugin_Imagine_Preset":266:{x:i:2;a:8:{s:5:"width";i:100;s:6:"height";i:100;s:4:"mode";s:5:"inset";s:9:"extension";N;s:7:"options";a:2:{s:12:"jpeg_quality";i:75;s:21:"png_compression_level";i:7;}s:8:"__module";N;s:9:"__imagine";N;s:16:"__transformation";N;};m:a:1:{s:7:"*name";s:7:"default";}}}"
Warning: Class __PHP_Incomplete_Class has no unserializes

the class `SystemPlugin_Imagine_Preset` has no unserialize method (or serialize) and so the error. Since this class has been in Zikula for sometime, I don't understand why it is now a problem. maybe it is a PHP version change issue?

### Steps to reproduce

php app/console debug:event-dispatcher -vvv

pretty sure this is an upgraded database... maybe it could be checked with a 1.4.3 db and see if it is the same behavior.

Also - because it is only a PHP WARNING, it doesn't stop the site from functioning.

**Comment by craigh** [comment] 2016-08-14 22:43
> maybe it could be checked with a 1.4.3 db and see if it is the same behavior.

done - behavior is the same with new 1.4.3 DB.

@cmfcmf  since you are using Imagine, can you take this one?

**Comment by Guite** [comment] 2016-08-15 04:54
Duplicate of #2883

**Closed** 2016-08-15 11:20 UTC
Labels: Bug
