### ISSUE TITLE
Incorrect License at Installer?

### ISSUE THREAD

**Issue by shefik** [zikula/core#2305] opened 2015-03-02 00:28 UTC
Isn't Zikula licensed under "GNU Lesser General Public License"?

http://www.gnu.org/licenses/lgpl.html

The installer just says "GPL license"

**Comment by cmfcmf** [comment] 2015-03-03 17:22
This is a duplicate of https://github.com/zikula/core/issues/1028, if I'm correct.

**Comment by Guite** [comment] 2015-03-04 12:13
Maybe postpone this one to 2.0.0 instead of closing it?

**Comment by craigh** [comment] 2015-03-05 02:01
> The installer just says "GPL license"

where?

**Comment by shefik** [comment] 2015-03-05 02:58
@craigh It says "Zikula is free software released under the GPL license!" in this Twig template:

ZikulaCoreInstallerBundle:Install:notinstalled.html.twig

**Comment by craigh** [comment] 2017-04-01 01:56
I don't know enough about licensing

https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License#Differences_from_the_GPL

#1028 says:

> @phaidon Shouldn't be Lesser GNU General Public License?

> Drak: No. Not at the moment, until we replace the gettext implementations with non-GPL versions

I know I have removed the old Gettext functions, but I don't know if that is what drak was referring to. So I don't know how to proceed with this ticket.

**Comment by Guite** [comment] 2017-04-01 06:40
I guess that as soon as there are no old GPL-licensed files contained in the core anymore, we can properly relicense as LGPL.

**Comment by craigh** [comment] 2017-04-01 11:37
but how do we know?

**Comment by Guite** [comment] 2017-04-08 10:04
> but how do we know?

Guess: if all legacy code is gone, only vendors and newly written code remains.

**Comment by craigh** [comment] 2017-04-09 11:54
> only vendors and newly written code remains.

I don't believe this to be true. There may be a way to actually analyze the code/commits but I think we must assume that every byte in the code is **not** written since 1.4.0. In PhpStorm, you can 'annotate' each line of code and see who committed it and when (commit id). Names pop up there that haven't been involved since at least 0.8/1.0 if not earlier.

> I don't know enough about licensing

so I don't know how this all works.

**Comment by craigh** [comment] 2017-05-08 21:32
https://www.gnu.org/software/gettext/manual/html_node/Licenses.html
https://www.gnu.org/software/gettext/manual/html_node/Discussions.html

**Comment by craigh** [comment] 2017-05-13 16:47
https://choosealicense.com

**Comment by craigh** [comment] 2017-05-13 16:49
https://github.com/aFarkas/webshim#license

**Comment by craigh** [comment] 2017-05-14 11:46
https://opensource.stackexchange.com/questions/1711/combining-code-written-under-different-licenses-eiffel-forum-license-mit-and-a

**Comment by craigh** [comment] 2017-05-14 11:52
https://opensource.stackexchange.com/questions/5480/how-to-audit-licensing-of-old-project

**Comment by craigh** [comment] 2017-05-14 12:10
https://github.com/grosser/organization_license_audit

**Closed** 2020-04-10 10:53 UTC
Labels: Bug, Core Install/Upgrade
