### ISSUE TITLE
cannot re-activate modules after upgrade to 1.4.4-build152

### ISSUE THREAD

**Issue by MrMontesa** [zikula/core#3226] opened 2016-11-29 11:42 UTC
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.4build152
| PHP Version       | 5.6.26

### Expected behavior
re-activation of modules shold not end up in stack-traces

### Actual behavior
after copying over News module folder and checking the extensions page, it properly sais: re-activate. On clicking the button the page ends up in stack trace as below:
```
[1] Symfony\Component\HttpKernel\Exception\NotFoundHttpException: Page not found.
    at n/a
        in /data/web/1/000/027/915/75642/htdocs/upgrade.amc-idstein/lib/Zikula/Bundle/CoreBundle/Controller/LegacyController.php line 128

    at Zikula\Bundle\CoreBundle\Controller\LegacyController->shortUrlAction(object(Zikula_Request_Http))
        in  line 

    at call_user_func_array(array(object(LegacyController), 'shortUrlAction'), array(object(Zikula_Request_Http)))
        in /data/web/1/000/027/915/75642/htdocs/upgrade.amc-idstein/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 144

    at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Zikula_Request_Http), '1')
        in /data/web/1/000/027/915/75642/htdocs/upgrade.amc-idstein/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 64

    at Symfony\Component\HttpKernel\HttpKernel->handle(object(Zikula_Request_Http), '1', true)
        in /data/web/1/000/027/915/75642/htdocs/upgrade.amc-idstein/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php line 69

    at Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(object(Zikula_Request_Http), '1', true)
        in /data/web/1/000/027/915/75642/htdocs/upgrade.amc-idstein/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php line 185

    at Symfony\Component\HttpKernel\Kernel->handle(object(Zikula_Request_Http))
        in /data/web/1/000/027/915/75642/htdocs/upgrade.amc-idstein/index.php line 23

```

### Steps to reproduce
-upgrade 1.4.3. to 1.4.4build152
- copy over News module folder
- click on re-activate link

**Comment by craigh** [comment] 2016-11-29 12:47
@Guite there is no part of the Core Upgrader that deals with Third party modules, so the problem is in the Extensions Module.

**Comment by Guite** [comment] 2016-11-29 13:06
Looks like this is the same problem as #3197

**Comment by craigh** [comment] 2016-11-29 13:11
are you changing subdomains to test the upgrade?

**Comment by MrMontesa** [comment] 2016-11-29 13:20
Yes, with updating custom_parameters file prior to exectuting the update.
Will check with same domain again.

**Comment by craigh** [comment] 2016-11-29 21:18
> Yes, with updating custom_parameters file prior to exectuting the update.

Do you mean changing the `router.request_context.base_url` and `router.request_context.host` values to match the new url?

**Comment by craigh** [comment] 2016-11-30 22:21
@MrMontesa  is #3197 you said that it worked...

**Comment by MrMontesa** [comment] 2016-12-01 06:31
Yeah, it definitely worked for me. Seems like it re occurred. I will test a bit later today and report back.

**Comment by craigh** [comment] 2016-12-01 13:42
closed by https://github.com/zikula/core/issues/3212#issuecomment-264174129

**Comment by MrMontesa** [comment] 2016-12-01 13:42
I just tested the latest build156 and was able to activate all modules after upgrade. The modules tested were: MediaModule, News, Content, PostCalendar, Scribite Addressbook

**Comment by craigh** [comment] 2016-12-01 13:43
thank you for retesting!

**Closed by craigh** 2016-12-01 13:42 UTC
Labels: Feedback required, unconfirmed
