### ISSUE TITLE
Not all assets are installed - installation not possible

### ISSUE THREAD

**Issue by Kaik** [zikula/core#2649] opened 2015-11-22 23:12 UTC
I have mentioned that on slack that there is asset installation problem.
Now I have checked and build 116 all assets are installed in web folder while in build 117 there are assets missing.
It is not a ci problem I can experience it on current 1.4 branch

**Comment by craigh** [comment] 2015-11-22 23:23
what is missing?

**Comment by Kaik** [comment] 2015-11-22 23:27
![screenshot from 2015-11-23 00-25-33](https://cloud.githubusercontent.com/assets/966910/11326986/ea50a1b4-9178-11e5-8b9a-dc0ee6fba54b.png)

**Comment by craigh** [comment] 2015-11-22 23:29
confirmed

**Comment by craigh** [comment] 2015-11-22 23:36
It stands to reason that something in https://github.com/zikula/core/commit/092041e788fd6d32ffebbebb7f08440b28821026 changed the build @cmfcmf although I cannot see anything obvious.

**Comment by craigh** [comment] 2015-11-22 23:38
> I have mentioned that on slack

both build 116 and 117 occurred today. your comments in slack were yesterday.

**Comment by Kaik** [comment] 2015-11-22 23:40
I think this is due to a change in assets management before UsersModule is used this might be due one of the bundles/composer has changed something.
Build #116 (20-Nov-2015 13:08:46)

**Comment by craigh** [comment] 2015-11-23 00:11
> before UsersModule

huh? what does UsersModule have to do with anything?

but yes you are correct,
build 116 was 20-Nov
build 117 was 22-Nov

**Comment by Kaik** [comment] 2015-11-23 00:14
> huh? what does UsersModule have to do with anything?
This one is UsersModule function.
>It stands to reason that something in 092041e changed...

**Comment by craigh** [comment] 2015-11-23 00:33
comparing the `docs/en/Composer_Vendors.md` file from both builds shows no difference in versions. 

but several vendors are targeted at "dev-master" and are not under our direct control:

 - `elao/web-profiler-extra-bundle` has had no recent changes
 - `jms/translation-bundle` has had no recent changes
 - `phpids/phpids` has had no recent changes
 - `oyejorge/less.php dev-master` has seen [several updates](https://github.com/oyejorge/less.php/commits/master)

so the obvious candidate is less.php I guess.

**Comment by craigh** [comment] 2015-11-23 00:39
if I delete ALL my vendors and ALL my assets in web/* and then do
`composer install`

I cannot duplicate the problem. It still works for me locally.

**Comment by craigh** [comment] 2015-11-23 00:49
sadly, forcing less.php to an earlier version did not solve the problem. :frowning:

**Comment by craigh** [comment] 2015-11-23 00:52
@Kaik said:
> It is not a ci problem I can experience it on current 1.4 branch

how did you experience it?

maybe @cmfcmf will have some ideas tomorrow.

**Comment by craigh** [comment] 2015-11-23 02:39
Build 116 has:
![screen shot 2015-11-22 at 9 36 16 pm](https://cloud.githubusercontent.com/assets/350048/11328902/2d69fcba-9161-11e5-8161-588b3a71d326.png)
build 117 has:
![screen shot 2015-11-22 at 9 36 32 pm](https://cloud.githubusercontent.com/assets/350048/11328903/2ea0bf24-9161-11e5-9c46-94e2f67b4f81.png)

all of the missing stuff seems to have something to do with the [component-installer](https://github.com/RobLoach/component-installer)

**Comment by cmfcmf** [comment] 2015-11-23 11:48
Maybe related: https://github.com/RobLoach/component-installer/issues/94

Craig Heydenburg <notifications@github.com> schrieb am Mo., 23. Nov. 2015
03:39:

**Comment by Kaik** [comment] 2015-11-23 11:50
>how did you experience it?

Just fetched core + composer install.
You said that: 
>if I delete ALL my vendors and ALL my assets in web/* and then do
composer install
I cannot duplicate the problem. It still works for me locally.

I started with empty folder well only project and git no composer no composer.lock only IDE and git files and then hard reset with working directory.

**Comment by craigh** [comment] 2015-11-23 12:26
I updated composer to latest (I had an earlier version before) and I deleted entire contents of `/web` and `/vendors` and I also deleted `composer.lock` and still I have the correct assets after `composer install` so I still cannot reproduce locally.

**Comment by craigh** [comment] 2015-11-23 14:24
I was able to duplicate the problem locally by following the `build.xml` script:

```
> composer install  --prefer-dist --no-dev --no-scripts --ignore-platform-reqs
...
> php src/app/console assets:install src/web
```

**Comment by craigh** [comment] 2015-11-23 15:35
refs https://github.com/composer/composer/issues/4630

**Comment by craigh** [comment] 2015-11-23 16:50
build 127 is now correct

http://ci.zikula.org/job/Zikula_Core-1.4.1/127/

**Comment by craigh** [comment] 2015-11-23 17:09
maybe fixed by https://github.com/zikula/core/commit/fd6eac53a3cf50605beee3ab7d2d2f4331df6c14

**Comment by rallek** [comment] 2015-11-23 19:28
I am able to install ci.build 127

**Comment by craigh** [comment] 2015-11-23 19:30
thanks for testing Ralf.

**Closed** 2015-11-23 19:42 UTC
Labels: Blocker, Bug, CI Build

**Comment by craigh** [comment] 2015-11-23 21:04
I think https://github.com/composer/composer/issues/4626 was the root cause of this issue.
