### ISSUE TITLE
zikula-admin-hiddenpanel-menu not working after upgrade

### ISSUE THREAD

**Issue by MrMontesa** [zikula/core#3212] opened 2016-11-24 09:45 UTC
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.4-dev-build140
| PHP Version       | 5.6.25

### Expected behavior
Klicking on the admin menue strips in the main header menue should pop out the admin menue on the left hand side

### Actual behavior
The menue does not pop out when clicking on the admin menue link in the header menu. Tested on Andreas08 and Bootstrap theme

### Steps to reproduce
Upgraded from 1.4.3 to 1.4.4-build140
Since then admin menue does not work any longer

Tested with fresh install of build140. There it works as expected. Also menue worked with no issues on 1.4.3 installation.

**Comment by craigh** [comment] 2016-11-24 16:03
in the upgraded environment, what is the setting for `zikula_asset_manager.combine` in `custom_parameters.yml`?

**Comment by craigh** [comment] 2016-11-24 16:03
if `true`, please set to `false` and see if behavior continues.

**Comment by MrMontesa** [comment] 2016-11-25 10:31
It is set to false already. 
```
grep asset_manager.comb upgrade.amc-idstein/app/config/custom_parameters.yml
    zikula_asset_manager.combine: false
```
Is that introduced in 1.4.4? My 1.4.3 install does not have it. But the 1.4.4 upgraded and fresh install both contain the value. The only difference I see is that new install have value `true` while upgrade has value `false`.

In fact I gave it a try and set it to `true` and emptied the cache. Now zikula-admin-hiddenpanel-menu is working again.

**Comment by craigh** [comment] 2016-11-27 18:59
please try this again with newest build and reconfirm behavior.

> btw: how does one enable the site again once its deactivated via admin > general settings?

are you presented with the lock screen? If so, click the button and login and reactivate.

**Comment by craigh** [comment] 2016-11-27 23:46
I've tested this with an upgrade from standard 1.4.3 install to 1.4.4-dev (= build 151) and it works as expected. Closing but if you continue to experience problems, please reopen.

**Comment by MrMontesa** [comment] 2016-11-29 11:30
Hmm, I was just testing build152 and behvior did not change. I have to admin that I moved the site to a different subdomain to the test is not 100% the same.
Will re-test using the same subdomain. Since my custom_config in 1.4.3 contains:
`zikula_asset_manager.combine: false`
Can you suggest the value it should have during and post update? 
Thanks much

**Comment by craigh** [comment] 2016-11-29 11:34
If the value is false, assets are not combined into one file. When you look at the source you will see multiple individual files. If the value is true, all assets are combined and cached into one file - you will see only one file in the source.

either value should work, but the caching may get messed up during the upgrade. You could try deleting the `app/cache/prod/assets/` directory and see if that helps.

**Comment by MrMontesa** [comment] 2016-11-29 11:56
Did upgrade from 1.4.3 to 1.4.4 again which worked fine.
Then removed app/cache/prod/assets folder and tried accessing admin-menue with no luck.
assets folder got re-created containing a css and a js folder which do not contain any files/folders

```
[user@w31 ~/htdocs/upgrade.amc-idstein/app/cache/prod/assets]$ ls -al *
css:
total 8
drwxr-x---  2 27915f16910  www  512 Nov 29 12:53 .
drwxr-x---  4 27915f16910  www  512 Nov 29 12:53 ..

js:
total 8
drwxr-x---  2 27915f16910  www  512 Nov 29 12:53 .
drwxr-x---  4 27915f16910  www  512 Nov 29 12:53 ..
```

`zikula_asset_manager.combine` is still set to `false`.

**Comment by craigh** [comment] 2016-11-29 12:49
is this on the same subdomain?

**Comment by Guite** [comment] 2016-11-30 14:00
I have a similar problem on a fresh install with `zikula_asset_manager.combine` set to `false`. The FireBug console shows:

`TypeError: a(...).mmenu is not a function` in `system/AdminModule/Resources/public/js/ZikulaAdminModule.Modules.Panel.MMenuConfig.js`.

This seems to be caused by
`<script type="text/javascript" src="//vendor/jQuery.mmenu/dist/js/jquery.mmenu.all.min.js"></script>` note the double `//` at the beginning of the path which is translated to `http://` by the browser.

**Comment by Guite** [comment] 2016-11-30 14:06
PR in #3229

**Closed** 2016-11-30 20:53 UTC
Labels: Bug, Core Install & Upgrade

**Comment by MrMontesa** [comment] 2016-12-01 13:34
Just tested with build156 and can confirm the issue is solved.
