### ISSUE TITLE
Unable to delete categories - Integrity constraint violation

### ISSUE THREAD

**Issue by shefik** [zikula/core#2884] opened 2016-05-22 04:27 UTC
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.2
| PHP Version       | 5.6

### Expected behavior

Using the UI, delete a category here:

`/categories/admin/view`

### Actual behavior

Error thrown:

```
An exception occurred while executing 'DELETE FROM categories_category WHERE id = ?' with params [42]: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`database_name`.`categories_category`, CONSTRAINT `FK_D0B2B0F8727ACA70` FOREIGN KEY (`parent_id`) REFERENCES `categories_category` (`id`))
```

### Steps to reproduce

Install the Pages module, and then try to delete the parent category "Pages", along with its subcategories.

**Comment by Guite** [comment] 2016-07-13 07:31
Any idea how to approach this @zikula/contributors

**Comment by cmfcmf** [comment] 2016-08-14 19:30
@shefik You wrote Zikula version 1.**3**.2. I assume you mean 1.**4**.2?

**Comment by shefik** [comment] 2016-08-14 22:44
@cmfcmf Yes, I did mean 1.4.2.

**Comment by craigh** [comment] 2016-08-16 00:48
> Any idea how to approach this?

this is an issue where the foreign key entities have to be removed before the 'parent'. Or a cascade must be set to do so automatically. (And then called properly from doctrine).

I had noticed this behavior before and forgot to do anything about it.

**Comment by Guite** [comment] 2016-08-19 08:05
Proposal: when a category should be deleted do the following:
1. iterate over all registries
2. for each registry check if the corresponding subtree contains this category
3. if yes check if the mapping table contains a reference to this category
4. if yes abort with an error

**Comment by cmfcmf** [comment] 2016-08-19 08:09
> Proposal: when a category should be deleted do the following:
> 1. iterate over all registries

I've never used categories so I don't fully grasp how they work, but your proposal sounds alright.

**Comment by Guite** [comment] 2016-08-19 08:10
Modules register category registries pointing to category subtrees. This allows having different sets of categories, but also reusing them across different modules.

**Comment by Guite** [comment] 2016-08-19 09:03
This needs also applied to _move_ actions.

**Comment by Guite** [comment] 2016-08-19 12:41
Fixed in #2985

**Closed by Guite** 2016-08-19 12:41 UTC
Labels: Bug, ZCS

**Comment by shefik** [comment] 2016-11-03 02:46
This issue does not appear to be fixed in Zikula 1.4.3. I am experiencing the same error:

`An exception occurred while executing 'DELETE FROM categories_category WHERE id = ?' with params [42]: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`database_name`.`categories_category`, CONSTRAINT `FK_D0B2B0F8727ACA70` FOREIGN KEY (`parent_id`) REFERENCES `categories_category` (`id`))`

**Comment by Guite** [comment] 2016-11-03 06:59
Did you try to delete a category which is used in Pages? This is what should be fixed. Or did you try to delete a category containing a category which is used? This is probably not fixed yet, so the checks must be enhanced to be executed also for potentially affected subcategories. See #3133

**Comment by shefik** [comment] 2016-11-03 07:07
@Guite The only thing I am doing is inserting this one-line within a module's `uninstall` function:

`CategoryUtil::deleteCategoriesByPath('/__SYSTEM__/Modules/'.$this->bundle->getName(), 'path');`

The error gets thrown, based on just that one line.

**Comment by Guite** [comment] 2016-11-03 07:15
So you are trying a category which *contains* categories used. This is what #3133 is about. #2985 added the check only for deleting used categories directly (instead of one of it's parents).

But also after #3133 is done it will still raise an error, if a sub category of the one to be deleted is still used. It will be a more readable error though.

**Comment by shefik** [comment] 2016-11-03 07:19
Ok, thanks. I understand the issue now. Perhaps it will be useful to add functionality to recursively delete the subcategories too, instead of just making the error more readable, if an additional `true` parameter is passed to `CategoryUtil::deleteCategoriesByPath` to force delete?

**Comment by Guite** [comment] 2016-11-03 07:52
This is what is currently done. The problem is when a sub category is used (assigned in any module's entity) you will still get the integrity constraint failure. #3133 is just about recognising this before and raising a more understandable message instead.
