### ISSUE TITLE
creating a new menu item not possible

### ISSUE THREAD

**Issue by rallek** [zikula/core#2610] opened 2015-09-28 18:46 UTC
in 1.4.1 ci build 70 I can not add a new menu item. If I click the link ``Create new menu item`` the site is jumping to the top.

The link is pointing to ``http://mysite.tld/blocks/admin/modify/1#``

**Comment by craigh** [comment] 2015-09-30 21:00
In my current Asset Improvement branch, I cannot reproduce the behavior. So maybe test again after the branch has been merged. 

refs https://github.com/zikula/core/pull/2606

**Comment by craigh** [comment] 2015-10-01 21:49
@rallek the branch has been merged. please test again.

**Comment by rallek** [comment] 2015-10-08 19:27
test is negativ. I do have still the same problem :-(

**Comment by rallek** [comment] 2015-10-13 05:42
Has it to do with #2626? Looks like a drag and drop or ajax issue.

**Comment by craigh** [comment] 2015-11-07 00:53
I still cannot reproduce this bug.

**Comment by rallek** [comment] 2015-11-08 12:37
and I do have still the same problem. In an absolutely fresh install of ci.build 104 I can not add an new menu item. 
I scroll down the site so ``Create new menu item`` is visble. Clicking on this link the page jumps back so I see the begin of the page and no additional menu item was created.

The installation is done on a shared hosting (webgo, not allinkl!) what is using Linux.

**Comment by craigh** [comment] 2015-11-08 12:43
do you know how to view the source html of the page? If so, please copy/paste the contents of `<head>` here.

**Comment by rallek** [comment] 2015-11-08 12:49
Here you are:
````
<head>
        <meta charset="utf8" />
        <title>Site name</title>
        <meta name="description" content="Site description" />
        <meta name="keywords" content="zikula, portal, open source, web site, website, weblog, blog, content management system, cms, application framework" />
        
        
    <link rel="stylesheet" href="/web/bootstrap-font-awesome.css" type="text/css">
<link rel="stylesheet" href="/style/core.css" type="text/css">
<link rel="stylesheet" href="/style/legacy.css" type="text/css">
<link rel="stylesheet" href="/system/BlocksModule/Resources/public/css/style.css" type="text/css">
<link rel="stylesheet" href="/system/BlocksModule/Resources/public/css/extmenu_modify.css" type="text/css">
<link rel="stylesheet" href="/system/AdminModule/Resources/public/css/style.css" type="text/css">
<link rel="stylesheet" href="/javascript/helpers/Zikula.UI.css" type="text/css">
<link rel="stylesheet" href="/system/AdminModule/Resources/public/js/jQuery.mmenu-5.5.1/dist/core/css/jquery.mmenu.all.css" type="text/css">
<link rel="stylesheet" href="/system/AdminModule/Resources/public/css/mmenu-hiddenpanel-customwidth.css" type="text/css">
<link rel="stylesheet" href="/themes/Andreas08Theme/Resources/public/css/style.css" type="text/css">
<link rel="stylesheet" href="/web/bootstrap/css/bootstrap-theme.min.css" type="text/css">
<script type="text/javascript">/* <![CDATA[ */ 
document.location.entrypoint="index.php";document.location.pnbaseURL="http://koester123.de/"; document.location.ajaxtimeout=5000;
if (typeof(Zikula) == 'undefined') {var Zikula = {};}
Zikula.Config = {"entrypoint":"index.php","baseURL":"http:\/\/koester123.de\/","baseURI":"\/","ajaxtimeout":"5000","lang":"en","sessionName":"_zsid","uid":"2"}
 /* ]]> */</script>
<script type="text/javascript" src="javascript/ajax/proto_scriptaculous.combined.min.js"></script>
<script type="text/javascript" src="/web/jquery/jquery.min.js"></script>
<script type="text/javascript" src="/web/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/javascript/helpers/bootstrap-zikula.js"></script>
<script type="text/javascript" src="/web/html5shiv/dist/html5shiv.js"></script>
<script type="text/javascript" src="/web/bundles/fosjsrouting/js/router.js"></script>
<script type="text/javascript" src="/web/js/fos_js_routes.js"></script>
<script type="text/javascript" src="web/jquery/jquery.min.js"></script>
<script type="text/javascript" src="javascript/jquery_config.js"></script>
<script type="text/javascript" src="web/jquery/jquery-migrate.min.js"></script>
<script type="text/javascript" src="javascript/livepipe/livepipe.combined.min.js"></script>
<script type="text/javascript" src="javascript/helpers/Zikula.js"></script>
<script type="text/javascript" src="javascript/helpers/Zikula.UI.js"></script>
<script type="text/javascript" src="javascript/helpers/Zikula.itemlist.js"></script>
<script type="text/javascript" src="web/bundles/fosjsrouting/js/router.js"></script>
<script type="text/javascript" src="web/js/fos_js_routes.js"></script>
<script type="text/javascript" src="web/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="javascript/helpers/bootstrap-zikula.js"></script>
<script type="text/javascript" src="system/AdminModule/Resources/public/js/admin_admin_systemnotices.js"></script>
<script type="text/javascript" src="system/AdminModule/Resources/public/js/admin_admin_admintabs.js"></script>
<script type="text/javascript" src="web/bootstrap-jqueryui/bootstrap-jqueryui.min.js"></script>
<script type="text/javascript" src="/system/AdminModule/Resources/public/js/jQuery.mmenu-5.5.1/dist/core/js/jquery.mmenu.min.all.js"></script>

<link rel="search" type="application/opensearchdescription+xml" title="Site name" href="/search/opensearch" />
    <script type="text/javascript">
        /* <![CDATA[ */
        var list_menuitemlist = null;
        document.observe('dom:loaded', function() {
            list_menuitemlist = new Zikula.itemlist('menuitemlist', {
                headerpresent: true,
                firstidiszero: true,
                recursive: true,
                inputName: 'linksorder'
            });
            $('appendmenuitem').observe('click', function(event) {
                list_menuitemlist.appenditem();
                event.stop();
            })
        });
        /* ]]> */
    </script>

<script type="text/javascript">
    /* <![CDATA[ */
    var total_existing_filters = 0;
    var list_placementfilterslist = null;
    var defwindow = null;
    document.observe("dom:loaded",function() {
        list_placementfilterslist = new Zikula.itemlist('placementfilterslist', {headerpresent: true, firstidiszero: true, sortable: false});
        $('appendfilter').observe('click', function(event) {
            list_placementfilterslist.appenditem();
            event.stop();
        });
        defwindow = new Zikula.UI.Dialog($('blocks_advanced_placement_onclick'),
        [{label: Zikula.__('Ok'), 'class': 'z-btgreen'}],
        {minmax:true, width: 760, height: 340, resizable: true}
        );
        $('blockupdateform').observe('submit', function() {
            $('blockupdateform').insert($('block_placement_advanced').hide());
        });
    });
    /* ]]> */
</script>
</head>
````

**Comment by craigh** [comment] 2015-11-08 13:18
is this site online publicly accessible?

**Comment by craigh** [comment] 2015-11-08 15:44
fixed by https://github.com/zikula/core/commit/d8fb5412498f98c14bb0e2f18f6f5c6d0e8d50b2

**Closed by craigh** 2015-11-08 15:44 UTC
Labels: Bug
